// ============================================================
// ClearUX — Supported Audit Languages
// Languages Claude can deliver professional UX audit content in
// ============================================================

export interface SupportedLanguage {
  code: string       // ISO 639-1
  label: string      // English name
  nativeLabel: string // Native name
  flag: string       // Emoji flag
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'en', label: 'English',    nativeLabel: 'English',   flag: '🇬🇧' },
  { code: 'es', label: 'Spanish',    nativeLabel: 'Español',   flag: '🇪🇸' },
  { code: 'fr', label: 'French',     nativeLabel: 'Français',  flag: '🇫🇷' },
  { code: 'de', label: 'German',     nativeLabel: 'Deutsch',   flag: '🇩🇪' },
  { code: 'it', label: 'Italian',    nativeLabel: 'Italiano',  flag: '🇮🇹' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português', flag: '🇧🇷' },
]

export const DEFAULT_LANGUAGE = 'en'

/** Get display label for a language code */
export function getLanguageLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.label : 'English'
}

/** Get native label for a language code */
export function getLanguageNativeLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.nativeLabel : 'English'
}

/** Build the language instruction for AI prompts */
export function getLanguagePromptInstruction(code: string): string {
  if (code === 'en') return '' // No extra instruction needed for English
  const lang = getLanguageLabel(code)
  return `\nIMPORTANT: Write your ENTIRE response in ${lang}. All findings, descriptions, recommendations, summaries, and scores must be written in ${lang}. Do NOT mix languages — everything must be in ${lang}.\n`
}

/** Static report section labels per language */
export interface ReportLabels {
  scoreBreakdown: string
  scoreSubtitle: string
  executiveSummary: string
  detailedFindings: string
  findingsSubtitle: string
  recommendation: string
  keyRecommendation: string
  pagesAnalysed: string
  pagesSubtitle: string
  issuesIdentified: string
  category: string
  score: string
  summary: string
  severity: string
  page: string
  title: string
  url: string
  status: string
  loadTime: string
  confidential: string
}

const REPORT_LABELS: Record<string, ReportLabels> = {
  en: { scoreBreakdown: 'Score Breakdown', scoreSubtitle: 'Performance across key UX dimensions', executiveSummary: 'Executive Summary', detailedFindings: 'Detailed Findings', findingsSubtitle: 'Issues and recommendations by priority', recommendation: 'Recommendation', keyRecommendation: 'Key Recommendation', pagesAnalysed: 'Pages Analysed', pagesSubtitle: 'Pages crawled and evaluated during this audit', issuesIdentified: 'issues identified', category: 'Category', score: 'Score', summary: 'Summary', severity: 'Severity', page: 'Page', title: 'Title', url: 'URL', status: 'Status', loadTime: 'Load Time', confidential: 'Confidential — Generated by ClearUX (clearux.ai)' },
  es: { scoreBreakdown: 'Desglose de Puntuación', scoreSubtitle: 'Rendimiento en dimensiones clave de UX', executiveSummary: 'Resumen Ejecutivo', detailedFindings: 'Hallazgos Detallados', findingsSubtitle: 'Problemas y recomendaciones por prioridad', recommendation: 'Recomendación', keyRecommendation: 'Recomendación Clave', pagesAnalysed: 'Páginas Analizadas', pagesSubtitle: 'Páginas rastreadas y evaluadas durante esta auditoría', issuesIdentified: 'problemas identificados', category: 'Categoría', score: 'Puntuación', summary: 'Resumen', severity: 'Severidad', page: 'Página', title: 'Título', url: 'URL', status: 'Estado', loadTime: 'Tiempo de Carga', confidential: 'Confidencial — Generado por ClearUX (clearux.ai)' },
  fr: { scoreBreakdown: 'Analyse des Scores', scoreSubtitle: 'Performance sur les dimensions clés de l\'UX', executiveSummary: 'Résumé Exécutif', detailedFindings: 'Résultats Détaillés', findingsSubtitle: 'Problèmes et recommandations par priorité', recommendation: 'Recommandation', keyRecommendation: 'Recommandation Clé', pagesAnalysed: 'Pages Analysées', pagesSubtitle: 'Pages explorées et évaluées lors de cet audit', issuesIdentified: 'problèmes identifiés', category: 'Catégorie', score: 'Score', summary: 'Résumé', severity: 'Sévérité', page: 'Page', title: 'Titre', url: 'URL', status: 'Statut', loadTime: 'Temps de Chargement', confidential: 'Confidentiel — Généré par ClearUX (clearux.ai)' },
  de: { scoreBreakdown: 'Bewertungsübersicht', scoreSubtitle: 'Leistung in den wichtigsten UX-Dimensionen', executiveSummary: 'Zusammenfassung', detailedFindings: 'Detaillierte Ergebnisse', findingsSubtitle: 'Probleme und Empfehlungen nach Priorität', recommendation: 'Empfehlung', keyRecommendation: 'Wichtigste Empfehlung', pagesAnalysed: 'Analysierte Seiten', pagesSubtitle: 'Während dieses Audits gecrawlte und bewertete Seiten', issuesIdentified: 'Probleme identifiziert', category: 'Kategorie', score: 'Bewertung', summary: 'Zusammenfassung', severity: 'Schweregrad', page: 'Seite', title: 'Titel', url: 'URL', status: 'Status', loadTime: 'Ladezeit', confidential: 'Vertraulich — Erstellt von ClearUX (clearux.ai)' },
  it: { scoreBreakdown: 'Riepilogo Punteggi', scoreSubtitle: 'Performance nelle dimensioni chiave della UX', executiveSummary: 'Sintesi Esecutiva', detailedFindings: 'Risultati Dettagliati', findingsSubtitle: 'Problemi e raccomandazioni per priorità', recommendation: 'Raccomandazione', keyRecommendation: 'Raccomandazione Chiave', pagesAnalysed: 'Pagine Analizzate', pagesSubtitle: 'Pagine scansionate e valutate durante questo audit', issuesIdentified: 'problemi identificati', category: 'Categoria', score: 'Punteggio', summary: 'Riepilogo', severity: 'Severità', page: 'Pagina', title: 'Titolo', url: 'URL', status: 'Stato', loadTime: 'Tempo di Caricamento', confidential: 'Riservato — Generato da ClearUX (clearux.ai)' },
  pt: { scoreBreakdown: 'Detalhamento da Pontuação', scoreSubtitle: 'Desempenho nas principais dimensões de UX', executiveSummary: 'Resumo Executivo', detailedFindings: 'Descobertas Detalhadas', findingsSubtitle: 'Problemas e recomendações por prioridade', recommendation: 'Recomendação', keyRecommendation: 'Recomendação Principal', pagesAnalysed: 'Páginas Analisadas', pagesSubtitle: 'Páginas rastreadas e avaliadas durante esta auditoria', issuesIdentified: 'problemas identificados', category: 'Categoria', score: 'Pontuação', summary: 'Resumo', severity: 'Severidade', page: 'Página', title: 'Título', url: 'URL', status: 'Status', loadTime: 'Tempo de Carregamento', confidential: 'Confidencial — Gerado por ClearUX (clearux.ai)' },
}

/** Get translated report labels for a language */
export function getReportLabels(code: string): ReportLabels {
  return REPORT_LABELS[code] || REPORT_LABELS['en']
}

/** Translated UX category names — order must match UX_CATEGORIES in analyzer.ts (16 categories, 4 per pillar) */
const CATEGORY_NAMES: Record<string, string[]> = {
  en: [
    // Foundation (1-4)
    'Visual Design & First Impression',
    'Value Proposition & Messaging',
    'Navigation & Information Architecture',
    'Content Quality & Readability',
    // Human Experience (5-8)
    'Calls-to-Action & Conversion Path',
    'Trust, Credibility & Social Proof',
    'Ethical UX & Dark Pattern Detection',
    'Emotional Design & Psychological Safety',
    // Inclusive Design (9-12)
    'Accessibility & WCAG Compliance',
    'Cognitive Accessibility & Neurodiversity',
    'Digital Wellbeing & Responsible Design',
    'Mobile Experience & Responsive Design',
    // Future Readiness (13-16)
    'Performance & Technical Health',
    'AI Discoverability & LLM Readiness',
    'AI Agent Readiness',
    'Cultural Sensitivity & Global Readiness',
  ],
  es: [
    'Diseño Visual y Primera Impresión', 'Propuesta de Valor y Mensajes', 'Navegación y Arquitectura de la Información', 'Calidad del Contenido y Legibilidad',
    'Llamadas a la Acción y Ruta de Conversión', 'Confianza, Credibilidad y Prueba Social', 'UX Ético y Detección de Patrones Oscuros', 'Diseño Emocional y Seguridad Psicológica',
    'Accesibilidad y Cumplimiento WCAG', 'Accesibilidad Cognitiva y Neurodiversidad', 'Bienestar Digital y Diseño Responsable', 'Experiencia Móvil y Diseño Responsivo',
    'Rendimiento y Salud Técnica', 'Descubribilidad por IA y Preparación para LLM', 'Preparación para Agentes de IA', 'Sensibilidad Cultural y Preparación Global',
  ],
  fr: [
    'Design Visuel et Première Impression', 'Proposition de Valeur et Messages', 'Navigation et Architecture de l\'Information', 'Qualité du Contenu et Lisibilité',
    'Appels à l\'Action et Parcours de Conversion', 'Confiance, Crédibilité et Preuve Sociale', 'UX Éthique et Détection de Dark Patterns', 'Design Émotionnel et Sécurité Psychologique',
    'Accessibilité et Conformité WCAG', 'Accessibilité Cognitive et Neurodiversité', 'Bien-être Numérique et Design Responsable', 'Expérience Mobile et Design Adaptatif',
    'Performance et Santé Technique', 'Découvrabilité IA et Préparation LLM', 'Préparation aux Agents IA', 'Sensibilité Culturelle et Préparation Mondiale',
  ],
  de: [
    'Visuelles Design und Erster Eindruck', 'Wertversprechen und Botschaften', 'Navigation und Informationsarchitektur', 'Inhaltsqualität und Lesbarkeit',
    'Handlungsaufforderungen und Konversionspfad', 'Vertrauen, Glaubwürdigkeit und Social Proof', 'Ethisches UX und Dark-Pattern-Erkennung', 'Emotionales Design und Psychologische Sicherheit',
    'Barrierefreiheit und WCAG-Konformität', 'Kognitive Barrierefreiheit und Neurodiversität', 'Digitales Wohlbefinden und Verantwortungsvolles Design', 'Mobile Erfahrung und Responsives Design',
    'Leistung und Technische Gesundheit', 'KI-Auffindbarkeit und LLM-Bereitschaft', 'KI-Agenten-Bereitschaft', 'Kulturelle Sensibilität und Globale Bereitschaft',
  ],
  it: [
    'Design Visivo e Prima Impressione', 'Proposta di Valore e Messaggi', 'Navigazione e Architettura dell\'Informazione', 'Qualità dei Contenuti e Leggibilità',
    'Chiamate all\'Azione e Percorso di Conversione', 'Fiducia, Credibilità e Riprova Sociale', 'UX Etico e Rilevamento Dark Pattern', 'Design Emotivo e Sicurezza Psicologica',
    'Accessibilità e Conformità WCAG', 'Accessibilità Cognitiva e Neurodiversità', 'Benessere Digitale e Design Responsabile', 'Esperienza Mobile e Design Responsivo',
    'Prestazioni e Salute Tecnica', 'Scopribilità IA e Preparazione LLM', 'Preparazione per Agenti IA', 'Sensibilità Culturale e Preparazione Globale',
  ],
  pt: [
    'Design Visual e Primeira Impressão', 'Proposta de Valor e Mensagens', 'Navegação e Arquitetura da Informação', 'Qualidade do Conteúdo e Legibilidade',
    'Chamadas para Ação e Caminho de Conversão', 'Confiança, Credibilidade e Prova Social', 'UX Ético e Detecção de Dark Patterns', 'Design Emocional e Segurança Psicológica',
    'Acessibilidade e Conformidade WCAG', 'Acessibilidade Cognitiva e Neurodiversidade', 'Bem-estar Digital e Design Responsável', 'Experiência Mobile e Design Responsivo',
    'Desempenho e Saúde Técnica', 'Descobribilidade por IA e Preparação para LLM', 'Preparação para Agentes de IA', 'Sensibilidade Cultural e Preparação Global',
  ],
}

/** Get translated category names for a language */
export function getCategoryNames(code: string): string[] {
  return CATEGORY_NAMES[code] || CATEGORY_NAMES['en']
}

/** Get locale string for date formatting */
export function getLocale(code: string): string {
  const localeMap: Record<string, string> = {
    en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE', it: 'it-IT', pt: 'pt-BR',
  }
  return localeMap[code] || 'en-US'
}
