// ============================================================
// ClearUX — Supported Audit Languages
// Languages Claude can deliver professional UX audit content in
// ============================================================

export interface SupportedLanguage {
  code: string       // ISO 639-1
  label: string      // English name
  nativeLabel: string // Native name
  flag: string       // Emoji flag
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'en', label: 'English',    nativeLabel: 'English',   flag: '🇬🇧' },
  { code: 'es', label: 'Spanish',    nativeLabel: 'Español',   flag: '🇪🇸' },
  { code: 'fr', label: 'French',     nativeLabel: 'Français',  flag: '🇫🇷' },
  { code: 'de', label: 'German',     nativeLabel: 'Deutsch',   flag: '🇩🇪' },
  { code: 'it', label: 'Italian',    nativeLabel: 'Italiano',  flag: '🇮🇹' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português', flag: '🇧🇷' },
]

export const DEFAULT_LANGUAGE = 'en'

/** Get display label for a language code */
export function getLanguageLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.label : 'English'
}

/** Get native label for a language code */
export function getLanguageNativeLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.nativeLabel : 'English'
}

/** Build the language instruction for AI prompts */
export function getLanguagePromptInstruction(code: string): string {
  if (code === 'en') return '' // No extra instruction needed for English
  const lang = getLanguageLabel(code)
  return `\nIMPORTANT: Write your ENTIRE response in ${lang}. All findings, descriptions, recommendations, summaries, and scores must be written in ${lang}. Do NOT mix languages — everything must be in ${lang}.\n`
}

/** Static report section labels per language */
export interface ReportLabels {
  scoreBreakdown: string
  scoreSubtitle: string
  executiveSummary: string
  detailedFindings: string
  findingsSubtitle: string
  recommendation: string
  keyRecommendation: string
  pagesAnalysed: string
  pagesSubtitle: string
  issuesIdentified: string
  category: string
  score: string
  summary: string
  severity: string
  page: string
  title: string
  url: string
  status: string
  loadTime: string
  confidential: string
}

const REPORT_LABELS: Record<string, ReportLabels> = {
  en: { scoreBreakdown: 'Score Breakdown', scoreSubtitle: 'Performance across key UX dimensions', executiveSummary: 'Executive Summary', detailedFindings: 'Detailed Findings', findingsSubtitle: 'Issues and recommendations by priority', recommendation: 'Recommendation', keyRecommendation: 'Key Recommendation', pagesAnalysed: 'Pages Analysed', pagesSubtitle: 'Pages crawled and evaluated during this audit', issuesIdentified: 'issues identified', category: 'Category', score: 'Score', summary: 'Summary', severity: 'Severity', page: 'Page', title: 'Title', url: 'URL', status: 'Status', loadTime: 'Load Time', confidential: 'Confidential — Generated by ClearUX (clearux.ai)' },
  es: { scoreBreakdown: 'Desglose de Puntuación', scoreSubtitle: 'Rendimiento en dimensiones clave de UX', executiveSummary: 'Resumen Ejecutivo', detailedFindings: 'Hallazgos Detallados', findingsSubtitle: 'Problemas y recomendaciones por prioridad', recommendation: 'Recomendación', keyRecommendation: 'Recomendación Clave', pagesAnalysed: 'Páginas Analizadas', pagesSubtitle: 'Páginas rastreadas y evaluadas durante esta auditoría', issuesIdentified: 'problemas identificados', category: 'Categoría', score: 'Puntuación', summary: 'Resumen', severity: 'Severidad', page: 'Página', title: 'Título', url: 'URL', status: 'Estado', loadTime: 'Tiempo de Carga', confidential: 'Confidencial — Generado por ClearUX (clearux.ai)' },
  fr: { scoreBreakdown: 'Analyse des Scores', scoreSubtitle: 'Performance sur les dimensions clés de l\'UX', executiveSummary: 'Résumé Exécutif', detailedFindings: 'Résultats Détaillés', findingsSubtitle: 'Problèmes et recommandations par priorité', recommendation: 'Recommandation', keyRecommendation: 'Recommandation Clé', pagesAnalysed: 'Pages Analysées', pagesSubtitle: 'Pages explorées et évaluées lors de cet audit', issuesIdentified: 'problèmes identifiés', category: 'Catégorie', score: 'Score', summary: 'Résumé', severity: 'Sévérité', page: 'Page', title: 'Titre', url: 'URL', status: 'Statut', loadTime: 'Temps de Chargement', confidential: 'Confidentiel — Généré par ClearUX (clearux.ai)' },
  de: { scoreBreakdown: 'Bewertungsübersicht', scoreSubtitle: 'Leistung in den wichtigsten UX-Dimensionen', executiveSummary: 'Zusammenfassung', detailedFindings: 'Detaillierte Ergebnisse', findingsSubtitle: 'Probleme und Empfehlungen nach Priorität', recommendation: 'Empfehlung', keyRecommendation: 'Wichtigste Empfehlung', pagesAnalysed: 'Analysierte Seiten', pagesSubtitle: 'Während dieses Audits gecrawlte und bewertete Seiten', issuesIdentified: 'Probleme identifiziert', category: 'Kategorie', score: 'Bewertung', summary: 'Zusammenfassung', severity: 'Schweregrad', page: 'Seite', title: 'Titel', url: 'URL', status: 'Status', loadTime: 'Ladezeit', confidential: 'Vertraulich — Erstellt von ClearUX (clearux.ai)' },
  it: { scoreBreakdown: 'Riepilogo Punteggi', scoreSubtitle: 'Performance nelle dimensioni chiave della UX', executiveSummary: 'Sintesi Esecutiva', detailedFindings: 'Risultati Dettagliati', findingsSubtitle: 'Problemi e raccomandazioni per priorità', recommendation: 'Raccomandazione', keyRecommendation: 'Raccomandazione Chiave', pagesAnalysed: 'Pagine Analizzate', pagesSubtitle: 'Pagine scansionate e valutate durante questo audit', issuesIdentified: 'problemi identificati', category: 'Categoria', score: 'Punteggio', summary: 'Riepilogo', severity: 'Severità', page: 'Pagina', title: 'Titolo', url: 'URL', status: 'Stato', loadTime: 'Tempo di Caricamento', confidential: 'Riservato — Generato da ClearUX (clearux.ai)' },
  pt: { scoreBreakdown: 'Detalhamento da Pontuação', scoreSubtitle: 'Desempenho nas principais dimensões de UX', executiveSummary: 'Resumo Executivo', detailedFindings: 'Descobertas Detalhadas', findingsSubtitle: 'Problemas e recomendações por prioridade', recommendation: 'Recomendação', keyRecommendation: 'Recomendação Principal', pagesAnalysed: 'Páginas Analisadas', pagesSubtitle: 'Páginas rastreadas e avaliadas durante esta auditoria', issuesIdentified: 'problemas identificados', category: 'Categoria', score: 'Pontuação', summary: 'Resumo', severity: 'Severidade', page: 'Página', title: 'Título', url: 'URL', status: 'Status', loadTime: 'Tempo de Carregamento', confidential: 'Confidencial — Gerado por ClearUX (clearux.ai)' },
}

/** Get translated report labels for a language */
export function getReportLabels(code: string): ReportLabels {
  return REPORT_LABELS[code] || REPORT_LABELS['en']
}

/** Translated UX category names — order must match UX_CATEGORIES in analyzer.ts */
const CATEGORY_NAMES: Record<string, string[]> = {
  en: [
    'First Impression & Visual Design',
    'Value Proposition & Messaging',
    'Navigation & Information Architecture',
    'Calls-to-Action & Conversion',
    'Performance & Page Speed',
    'Mobile Experience',
    'Trust & Credibility',
    'Content Quality & Readability',
    'Technical SEO & Accessibility',
    'AI Discoverability & LLM Readiness',
    'Visual Hierarchy & Layout',
    'Accessibility & Inclusive Design',
  ],
  es: [
    'Primera Impresión y Diseño Visual',
    'Propuesta de Valor y Mensajes',
    'Navegación y Arquitectura de la Información',
    'Llamadas a la Acción y Conversión',
    'Rendimiento y Velocidad de Carga',
    'Experiencia Móvil',
    'Confianza y Credibilidad',
    'Calidad del Contenido y Legibilidad',
    'SEO Técnico y Accesibilidad',
    'Descubribilidad por IA y Preparación para LLM',
    'Jerarquía Visual y Diseño',
    'Accesibilidad y Diseño Inclusivo',
  ],
  fr: [
    'Première Impression et Design Visuel',
    'Proposition de Valeur et Messages',
    'Navigation et Architecture de l\'Information',
    'Appels à l\'Action et Conversion',
    'Performance et Vitesse de Chargement',
    'Expérience Mobile',
    'Confiance et Crédibilité',
    'Qualité du Contenu et Lisibilité',
    'SEO Technique et Accessibilité',
    'Découvrabilité IA et Préparation LLM',
    'Hiérarchie Visuelle et Mise en Page',
    'Accessibilité et Design Inclusif',
  ],
  de: [
    'Erster Eindruck und Visuelles Design',
    'Wertversprechen und Botschaften',
    'Navigation und Informationsarchitektur',
    'Handlungsaufforderungen und Konversion',
    'Leistung und Ladegeschwindigkeit',
    'Mobile Erfahrung',
    'Vertrauen und Glaubwürdigkeit',
    'Inhaltsqualität und Lesbarkeit',
    'Technisches SEO und Barrierefreiheit',
    'KI-Auffindbarkeit und LLM-Bereitschaft',
    'Visuelle Hierarchie und Layout',
    'Barrierefreiheit und Inklusives Design',
  ],
  it: [
    'Prima Impressione e Design Visivo',
    'Proposta di Valore e Messaggi',
    'Navigazione e Architettura dell\'Informazione',
    'Chiamate all\'Azione e Conversione',
    'Prestazioni e Velocità di Caricamento',
    'Esperienza Mobile',
    'Fiducia e Credibilità',
    'Qualità dei Contenuti e Leggibilità',
    'SEO Tecnico e Accessibilità',
    'Scopribilità IA e Preparazione LLM',
    'Gerarchia Visiva e Layout',
    'Accessibilità e Design Inclusivo',
  ],
  pt: [
    'Primeira Impressão e Design Visual',
    'Proposta de Valor e Mensagens',
    'Navegação e Arquitetura da Informação',
    'Chamadas para Ação e Conversão',
    'Desempenho e Velocidade de Carregamento',
    'Experiência Mobile',
    'Confiança e Credibilidade',
    'Qualidade do Conteúdo e Legibilidade',
    'SEO Técnico e Acessibilidade',
    'Descobribilidade por IA e Preparação para LLM',
    'Hierarquia Visual e Layout',
    'Acessibilidade e Design Inclusivo',
  ],
}

/** Get translated category names for a language */
export function getCategoryNames(code: string): string[] {
  return CATEGORY_NAMES[code] || CATEGORY_NAMES['en']
}

/** Get locale string for date formatting */
export function getLocale(code: string): string {
  const localeMap: Record<string, string> = {
    en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE', it: 'it-IT', pt: 'pt-BR',
  }
  return localeMap[code] || 'en-US'
}
