// ============================================================
// ClearUX — Supported Audit Languages
// Languages Claude can deliver professional UX audit content in
// ============================================================

export interface SupportedLanguage {
  code: string       // ISO 639-1
  label: string      // English name
  nativeLabel: string // Native name
  flag: string       // Emoji flag
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'en', label: 'English',    nativeLabel: 'English',   flag: '🇬🇧' },
  { code: 'es', label: 'Spanish',    nativeLabel: 'Español',   flag: '🇪🇸' },
  { code: 'fr', label: 'French',     nativeLabel: 'Français',  flag: '🇫🇷' },
  { code: 'de', label: 'German',     nativeLabel: 'Deutsch',   flag: '🇩🇪' },
  { code: 'it', label: 'Italian',    nativeLabel: 'Italiano',  flag: '🇮🇹' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português', flag: '🇧🇷' },
]

export const DEFAULT_LANGUAGE = 'en'

/** Get display label for a language code */
export function getLanguageLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.label : 'English'
}

/** Get native label for a language code */
export function getLanguageNativeLabel(code: string): string {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code)
  return lang ? lang.nativeLabel : 'English'
}

/** Build the language instruction for AI prompts */
export function getLanguagePromptInstruction(code: string): string {
  if (code === 'en') return '' // No extra instruction needed for English
  const lang = getLanguageLabel(code)
  return `\nIMPORTANT: Write your ENTIRE response in ${lang}. All findings, descriptions, recommendations, summaries, and scores must be written in ${lang}. Do NOT mix languages — everything must be in ${lang}.\n`
}

/** Static report section labels per language */
export interface ReportLabels {
  scoreBreakdown: string
  scoreSubtitle: string
  executiveSummary: string
  detailedFindings: string
  findingsSubtitle: string
  recommendation: string
  keyRecommendation: string
  pagesAnalysed: string
  pagesSubtitle: string
  issuesIdentified: string
  category: string
  score: string
  summary: string
  severity: string
  page: string
  title: string
  url: string
  status: string
  loadTime: string
  confidential: string
}

const REPORT_LABELS: Record<string, ReportLabels> = {
  en: { scoreBreakdown: 'Score Breakdown', scoreSubtitle: 'Performance across key UX dimensions', executiveSummary: 'Executive Summary', detailedFindings: 'Detailed Findings', findingsSubtitle: 'Issues and recommendations by priority', recommendation: 'Recommendation', keyRecommendation: 'Key Recommendation', pagesAnalysed: 'Pages Analysed', pagesSubtitle: 'Pages crawled and evaluated during this audit', issuesIdentified: 'issues identified', category: 'Category', score: 'Score', summary: 'Summary', severity: 'Severity', page: 'Page', title: 'Title', url: 'URL', status: 'Status', loadTime: 'Load Time', confidential: 'Confidential — Generated by ClearUX (clearux.ai)' },
  es: { scoreBreakdown: 'Desglose de Puntuación', scoreSubtitle: 'Rendimiento en dimensiones clave de UX', executiveSummary: 'Resumen Ejecutivo', detailedFindings: 'Hallazgos Detallados', findingsSubtitle: 'Problemas y recomendaciones por prioridad', recommendation: 'Recomendación', keyRecommendation: 'Recomendación Clave', pagesAnalysed: 'Páginas Analizadas', pagesSubtitle: 'Páginas rastreadas y evaluadas durante esta auditoría', issuesIdentified: 'problemas identificados', category: 'Categoría', score: 'Puntuación', summary: 'Resumen', severity: 'Severidad', page: 'Página', title: 'Título', url: 'URL', status: 'Estado', loadTime: 'Tiempo de Carga', confidential: 'Confidencial — Generado por ClearUX (clearux.ai)' },
  fr: { scoreBreakdown: 'Analyse des Scores', scoreSubtitle: 'Performance sur les dimensions clés de l\'UX', executiveSummary: 'Résumé Exécutif', detailedFindings: 'Résultats Détaillés', findingsSubtitle: 'Problèmes et recommandations par priorité', recommendation: 'Recommandation', keyRecommendation: 'Recommandation Clé', pagesAnalysed: 'Pages Analysées', pagesSubtitle: 'Pages explorées et évaluées lors de cet audit', issuesIdentified: 'problèmes identifiés', category: 'Catégorie', score: 'Score', summary: 'Résumé', severity: 'Sévérité', page: 'Page', title: 'Titre', url: 'URL', status: 'Statut', loadTime: 'Temps de Chargement', confidential: 'Confidentiel — Généré par ClearUX (clearux.ai)' },
  de: { scoreBreakdown: 'Bewertungsübersicht', scoreSubtitle: 'Leistung in den wichtigsten UX-Dimensionen', executiveSummary: 'Zusammenfassung', detailedFindings: 'Detaillierte Ergebnisse', findingsSubtitle: 'Probleme und Empfehlungen nach Priorität', recommendation: 'Empfehlung', keyRecommendation: 'Wichtigste Empfehlung', pagesAnalysed: 'Analysierte Seiten', pagesSubtitle: 'Während dieses Audits gecrawlte und bewertete Seiten', issuesIdentified: 'Probleme identifiziert', category: 'Kategorie', score: 'Bewertung', summary: 'Zusammenfassung', severity: 'Schweregrad', page: 'Seite', title: 'Titel', url: 'URL', status: 'Status', loadTime: 'Ladezeit', confidential: 'Vertraulich — Erstellt von ClearUX (clearux.ai)' },
  it: { scoreBreakdown: 'Riepilogo Punteggi', scoreSubtitle: 'Performance nelle dimensioni chiave della UX', executiveSummary: 'Sintesi Esecutiva', detailedFindings: 'Risultati Dettagliati', findingsSubtitle: 'Problemi e raccomandazioni per priorità', recommendation: 'Raccomandazione', keyRecommendation: 'Raccomandazione Chiave', pagesAnalysed: 'Pagine Analizzate', pagesSubtitle: 'Pagine scansionate e valutate durante questo audit', issuesIdentified: 'problemi identificati', category: 'Categoria', score: 'Punteggio', summary: 'Riepilogo', severity: 'Severità', page: 'Pagina', title: 'Titolo', url: 'URL', status: 'Stato', loadTime: 'Tempo di Caricamento', confidential: 'Riservato — Generato da ClearUX (clearux.ai)' },
  pt: { scoreBreakdown: 'Detalhamento da Pontuação', scoreSubtitle: 'Desempenho nas principais dimensões de UX', executiveSummary: 'Resumo Executivo', detailedFindings: 'Descobertas Detalhadas', findingsSubtitle: 'Problemas e recomendações por prioridade', recommendation: 'Recomendação', keyRecommendation: 'Recomendação Principal', pagesAnalysed: 'Páginas Analisadas', pagesSubtitle: 'Páginas rastreadas e avaliadas durante esta auditoria', issuesIdentified: 'problemas identificados', category: 'Categoria', score: 'Pontuação', summary: 'Resumo', severity: 'Severidade', page: 'Página', title: 'Título', url: 'URL', status: 'Status', loadTime: 'Tempo de Carregamento', confidential: 'Confidencial — Gerado por ClearUX (clearux.ai)' },
}

/** Get translated report labels for a language */
export function getReportLabels(code: string): ReportLabels {
  return REPORT_LABELS[code] || REPORT_LABELS['en']
}

/** Translated UX category names — order must match UX_CATEGORIES in analyzer.ts (19 categories) */
const CATEGORY_NAMES: Record<string, string[]> = {
  en: [
    // Foundation (1-6)
    'First Impression & Visual Design',
    'Value Proposition & Messaging',
    'Navigation & Information Architecture',
    'Visual Hierarchy & Layout',
    'Content Quality & Readability',
    'Calls-to-Action & Conversion',
    // Human Experience (7-12)
    'Trust & Credibility',
    'Ethical UX & Dark Pattern Detection',
    'Emotional Intelligence & Psychological Safety',
    'Cognitive Accessibility & Neurodiversity',
    'Digital Wellbeing & Responsible Design',
    'Age Inclusivity & Digital Literacy',
    // Technical Excellence (13-16)
    'Performance & Page Speed',
    'Mobile Experience',
    'Accessibility & Inclusive Design',
    'Technical SEO & Accessibility',
    // Future Readiness (17-19)
    'AI Discoverability & LLM Readiness',
    'AI Agent Readiness',
    'Cultural Sensitivity & Global Readiness',
  ],
  es: [
    'Primera Impresión y Diseño Visual', 'Propuesta de Valor y Mensajes', 'Navegación y Arquitectura de la Información', 'Jerarquía Visual y Diseño', 'Calidad del Contenido y Legibilidad', 'Llamadas a la Acción y Conversión',
    'Confianza y Credibilidad', 'UX Ético y Detección de Patrones Oscuros', 'Inteligencia Emocional y Seguridad Psicológica', 'Accesibilidad Cognitiva y Neurodiversidad', 'Bienestar Digital y Diseño Responsable', 'Inclusión por Edad y Alfabetización Digital',
    'Rendimiento y Velocidad de Carga', 'Experiencia Móvil', 'Accesibilidad y Diseño Inclusivo', 'SEO Técnico y Accesibilidad',
    'Descubribilidad por IA y Preparación para LLM', 'Preparación para Agentes de IA', 'Sensibilidad Cultural y Preparación Global',
  ],
  fr: [
    'Première Impression et Design Visuel', 'Proposition de Valeur et Messages', 'Navigation et Architecture de l\'Information', 'Hiérarchie Visuelle et Mise en Page', 'Qualité du Contenu et Lisibilité', 'Appels à l\'Action et Conversion',
    'Confiance et Crédibilité', 'UX Éthique et Détection de Dark Patterns', 'Intelligence Émotionnelle et Sécurité Psychologique', 'Accessibilité Cognitive et Neurodiversité', 'Bien-être Numérique et Design Responsable', 'Inclusion par Âge et Littératie Numérique',
    'Performance et Vitesse de Chargement', 'Expérience Mobile', 'Accessibilité et Design Inclusif', 'SEO Technique et Accessibilité',
    'Découvrabilité IA et Préparation LLM', 'Préparation aux Agents IA', 'Sensibilité Culturelle et Préparation Mondiale',
  ],
  de: [
    'Erster Eindruck und Visuelles Design', 'Wertversprechen und Botschaften', 'Navigation und Informationsarchitektur', 'Visuelle Hierarchie und Layout', 'Inhaltsqualität und Lesbarkeit', 'Handlungsaufforderungen und Konversion',
    'Vertrauen und Glaubwürdigkeit', 'Ethisches UX und Dark-Pattern-Erkennung', 'Emotionale Intelligenz und Psychologische Sicherheit', 'Kognitive Barrierefreiheit und Neurodiversität', 'Digitales Wohlbefinden und Verantwortungsvolles Design', 'Altersinklusion und Digitale Kompetenz',
    'Leistung und Ladegeschwindigkeit', 'Mobile Erfahrung', 'Barrierefreiheit und Inklusives Design', 'Technisches SEO und Barrierefreiheit',
    'KI-Auffindbarkeit und LLM-Bereitschaft', 'KI-Agenten-Bereitschaft', 'Kulturelle Sensibilität und Globale Bereitschaft',
  ],
  it: [
    'Prima Impressione e Design Visivo', 'Proposta di Valore e Messaggi', 'Navigazione e Architettura dell\'Informazione', 'Gerarchia Visiva e Layout', 'Qualità dei Contenuti e Leggibilità', 'Chiamate all\'Azione e Conversione',
    'Fiducia e Credibilità', 'UX Etico e Rilevamento Dark Pattern', 'Intelligenza Emotiva e Sicurezza Psicologica', 'Accessibilità Cognitiva e Neurodiversità', 'Benessere Digitale e Design Responsabile', 'Inclusione per Età e Alfabetizzazione Digitale',
    'Prestazioni e Velocità di Caricamento', 'Esperienza Mobile', 'Accessibilità e Design Inclusivo', 'SEO Tecnico e Accessibilità',
    'Scopribilità IA e Preparazione LLM', 'Preparazione per Agenti IA', 'Sensibilità Culturale e Preparazione Globale',
  ],
  pt: [
    'Primeira Impressão e Design Visual', 'Proposta de Valor e Mensagens', 'Navegação e Arquitetura da Informação', 'Hierarquia Visual e Layout', 'Qualidade do Conteúdo e Legibilidade', 'Chamadas para Ação e Conversão',
    'Confiança e Credibilidade', 'UX Ético e Detecção de Dark Patterns', 'Inteligência Emocional e Segurança Psicológica', 'Acessibilidade Cognitiva e Neurodiversidade', 'Bem-estar Digital e Design Responsável', 'Inclusão Etária e Literacia Digital',
    'Desempenho e Velocidade de Carregamento', 'Experiência Mobile', 'Acessibilidade e Design Inclusivo', 'SEO Técnico e Acessibilidade',
    'Descobribilidade por IA e Preparação para LLM', 'Preparação para Agentes de IA', 'Sensibilidade Cultural e Preparação Global',
  ],
}

/** Get translated category names for a language */
export function getCategoryNames(code: string): string[] {
  return CATEGORY_NAMES[code] || CATEGORY_NAMES['en']
}

/** Get locale string for date formatting */
export function getLocale(code: string): string {
  const localeMap: Record<string, string> = {
    en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE', it: 'it-IT', pt: 'pt-BR',
  }
  return localeMap[code] || 'en-US'
}
