// ============================================================
// Fixpath Proprietary Pipeline — Communication Layer
// ============================================================
//
// Builds the dual-layer communication model for each finding:
//   1. Plain-language layer (site owners, marketers, non-technical)
//   2. Technical layer (developers)
//
// Runs AFTER analysis, BEFORE insertion. Processes AnalysisFinding
// objects and attaches a `communication` JSONB payload.
//
// Also applies industry-aware naming rules:
//   - Navigation findings MUST name "menu" or "navigation menu"
//   - Hospitality/venue/event/service sites get explicit nav naming
//   - No generic terms like "interactive elements" or "focus indicators"
//
// For findings that lack AI-generated communication fields (e.g.
// from non-analyzer detection sources like wcag_checker, responsive_
// checker, structured_data), this module synthesizes plain-language
// from the existing title/description/recommendation fields.
// ============================================================

import type { FindingCommunication } from '@/types/database'
import type { AnalysisFinding, SiteProfile } from '../analyzer'

// ── Types ────────────────────────────────────────────────────

export interface FindingWithCommunication {
  communication: FindingCommunication | null
}

/**
 * Minimal shape for findings that come from non-analyzer sources
 * (responsive checker, WCAG checker, structured data, etc.)
 */
export interface GenericFinding {
  title: string
  description: string
  recommendation: string
  estimatedImpact?: string | null
  severity?: string
}

// ── Industry detection ───────────────────────────────────────

/** Industries where visible desktop navigation is especially critical */
const NAV_CRITICAL_INDUSTRIES = [
  'hospitality', 'hotel', 'restaurant', 'venue', 'event',
  'booking', 'service', 'real estate', 'healthcare', 'clinic',
  'spa', 'salon', 'gym', 'fitness', 'travel', 'tourism',
  'fintech', 'banking', 'insurance', 'saas', 'b2b',
  'education', 'university', 'school',
]

function isNavCriticalIndustry(siteProfile: SiteProfile | null): boolean {
  if (!siteProfile?.industryVertical) return true // default: treat as nav-critical
  const vertical = siteProfile.industryVertical.toLowerCase()
  return NAV_CRITICAL_INDUSTRIES.some(ind => vertical.includes(ind))
}

// ── Navigation-specific name enforcement ─────────────────────

/** Terms that indicate a navigation finding but use generic language */
const GENERIC_NAV_TERMS = [
  'interactive elements', 'interactive element',
  'focus indicators', 'focus indicator',
  'discoverability pattern', 'discoverability patterns',
  'mobile paradigm', 'navigation paradigm',
  'hamburger pattern', 'collapsible pattern',
  'responsive navigation pattern',
]

/** Check if a title/description is about navigation but uses generic language */
function isNavFindingWithGenericLanguage(title: string, description: string): boolean {
  const combined = `${title} ${description}`.toLowerCase()
  const isAboutNav = combined.includes('nav') || combined.includes('menu') ||
    combined.includes('hamburger') || combined.includes('sidebar') ||
    combined.includes('header links') || combined.includes('site links')
  const usesGenericTerms = GENERIC_NAV_TERMS.some(term => combined.includes(term))
  return isAboutNav && usesGenericTerms
}

/** Rewrite a generic nav title to be explicit */
function enforceNavNaming(titlePlain: string, description: string): string {
  const lower = titlePlain.toLowerCase()
  // Already explicit about menu/navigation
  if (lower.includes('menu') || lower.includes('navigation menu') || lower.includes('nav menu')) {
    return titlePlain
  }
  // About hidden hamburger on desktop
  if (lower.includes('hamburger') || lower.includes('hidden') || description.toLowerCase().includes('hamburger')) {
    return titlePlain.replace(/interactive elements?/gi, 'navigation menu')
      .replace(/focus indicators?/gi, 'navigation menu')
      .replace(/discoverability patterns?/gi, 'navigation menu')
      .replace(/navigation paradigm/gi, 'navigation menu')
      .replace(/mobile paradigm/gi, 'mobile-style menu')
  }
  // Generic fallback: prepend "Navigation menu: "
  if (isNavFindingWithGenericLanguage(titlePlain, description)) {
    return `Navigation menu: ${titlePlain}`
  }
  return titlePlain
}

// ── Communication builder from AnalysisFinding ───────────────

/**
 * Build FindingCommunication from an AnalysisFinding that was
 * generated by the analyzer (which now outputs communication fields).
 */
export function buildCommunicationFromAnalysis(
  finding: AnalysisFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication | null {
  // If the analyzer provided all mandatory plain-language fields, use them
  if (finding.titlePlain && finding.whatFound && finding.whyMatters && finding.fixPlain) {
    let titlePlain = finding.titlePlain

    // Enforce navigation naming rules
    if (isNavFindingWithGenericLanguage(titlePlain, finding.whatFound || finding.description)) {
      titlePlain = enforceNavNaming(titlePlain, finding.whatFound || finding.description)
    }

    // For nav-critical industries, strengthen nav-related language
    if (isNavCriticalIndustry(siteProfile) && isNavFinding(finding.title, finding.description)) {
      titlePlain = enforceNavNaming(titlePlain, finding.whatFound || finding.description)
    }

    return {
      title_plain: titlePlain,
      what_found: finding.whatFound,
      why_matters: finding.whyMatters,
      technical_note: finding.technicalNote || null,
      fix_plain: finding.fixPlain,
      fix_technical: finding.fixTechnical || null,
    }
  }

  // Fallback: synthesize from existing fields
  return synthesizeCommunication(finding, siteProfile)
}

/** Check if a finding is about navigation */
function isNavFinding(title: string, description: string): boolean {
  const combined = `${title} ${description}`.toLowerCase()
  return combined.includes('nav') || combined.includes('menu') ||
    combined.includes('hamburger') || combined.includes('header links') ||
    combined.includes('site links') || combined.includes('sidebar')
}

// ── Fallback synthesizer ─────────────────────────────────────

/**
 * Synthesize plain-language communication from existing finding fields.
 * Used when:
 *   1. The analyzer didn't return communication fields (shouldn't happen
 *      with the new prompt, but backward-safe)
 *   2. The finding came from a non-analyzer source (WCAG checker,
 *      responsive checker, structured data validator, etc.)
 */
export function synthesizeCommunication(
  finding: GenericFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication {
  const title = finding.title
  const desc = finding.description
  const rec = finding.recommendation
  const impact = finding.estimatedImpact || ''

  // Build a plain title — strip technical jargon if detected
  let titlePlain = stripTechnicalJargon(title)

  // Enforce nav naming
  if (isNavFinding(title, desc)) {
    titlePlain = enforceNavNaming(titlePlain, desc)
  }

  // Build "what we found" — first 2 sentences of description, simplified
  const whatFound = simplifyDescription(desc)

  // Build "why it matters" — use estimated_impact or extract from description
  const whyMatters = impact
    ? simplifyImpact(impact)
    : extractWhyFromDescription(desc)

  // Build plain fix — strip code blocks and technical details from recommendation
  const fixPlain = simplifyRecommendation(rec)

  // Technical note — keep full recommendation as-is
  const technicalNote = rec.length > fixPlain.length ? rec : null

  // Technical fix — extract code blocks or technical specifics
  const fixTechnical = extractTechnicalFix(rec)

  return {
    title_plain: titlePlain,
    what_found: whatFound,
    why_matters: whyMatters,
    technical_note: technicalNote,
    fix_plain: fixPlain,
    fix_technical: fixTechnical,
  }
}

// ── Text transformation helpers ──────────────────────────────

/** Common technical terms → plain-language replacements */
const JARGON_MAP: Array<[RegExp, string]> = [
  [/\bCTA\b/gi, 'call-to-action button'],
  [/\bDOM\b/gi, 'page structure'],
  [/\bARIA\b/gi, 'accessibility'],
  [/\bJSON-LD\b/gi, 'structured data'],
  [/\bSEO\b/gi, 'search visibility'],
  [/\balt text\b/gi, 'image description'],
  [/\balt attribute\b/gi, 'image description'],
  [/\bmeta description\b/gi, 'search result description'],
  [/\bviewport\b/gi, 'screen size'],
  [/\bCSS\b/g, 'styling'],
  [/\bHTML\b/g, 'page code'],
  [/\bsemantic\b/gi, 'meaningful'],
  [/\bresponsive\b/gi, 'mobile-friendly'],
  [/\breadability score\b/gi, 'readability'],
  [/\bWCAG\s*\d*\.?\d*\s*(AA|AAA)?/gi, 'accessibility standards'],
  [/\bheading hierarchy\b/gi, 'heading structure'],
  [/\bcanonical URL\b/gi, 'preferred web address'],
  [/\bstructured data\b/gi, 'machine-readable information'],
  [/\brender\b/gi, 'display'],
  [/\blazy load(ing)?\b/gi, 'delayed loading'],
]

function stripTechnicalJargon(text: string): string {
  let result = text
  for (const [pattern, replacement] of JARGON_MAP) {
    result = result.replace(pattern, replacement)
  }
  return result
}

/** Extract the first 2-3 sentences as a simplified description */
function simplifyDescription(description: string): string {
  // Remove code blocks
  let simplified = description.replace(/```[\s\S]*?```/g, '').trim()
  // Remove inline code
  simplified = simplified.replace(/`[^`]+`/g, (match) => {
    const inner = match.slice(1, -1)
    // If it looks like a CSS selector or code, replace with description
    if (inner.includes('.') || inner.includes('#') || inner.includes('<') || inner.includes('>')) {
      return 'the element'
    }
    return inner
  })
  // Take first 2-3 sentences
  const sentences = simplified.match(/[^.!?]+[.!?]+/g) || [simplified]
  const plain = sentences.slice(0, 3).join(' ').trim()
  return stripTechnicalJargon(plain) || simplified.slice(0, 300)
}

/** Simplify estimated_impact to plain language */
function simplifyImpact(impact: string): string {
  return stripTechnicalJargon(impact)
}

/** Extract "why it matters" from description when no impact is available */
function extractWhyFromDescription(description: string): string {
  const lower = description.toLowerCase()
  // Look for impact-related sentences
  const impactIndicators = [
    'this means', 'this causes', 'this results in', 'as a result',
    'users will', 'visitors will', 'customers will',
    'this makes it', 'this prevents', 'this reduces',
    'hurts', 'damages', 'weakens', 'confuses',
    'lost', 'missing', 'broken',
  ]
  const sentences = description.match(/[^.!?]+[.!?]+/g) || []
  for (const sentence of sentences) {
    const sentenceLower = sentence.toLowerCase()
    if (impactIndicators.some(ind => sentenceLower.includes(ind))) {
      return stripTechnicalJargon(sentence.trim())
    }
  }
  // Fallback: generic impact statement
  return 'This issue may affect how visitors experience and interact with your site.'
}

/** Strip code blocks and technical specifics from recommendation */
function simplifyRecommendation(recommendation: string): string {
  // Remove code blocks
  let simplified = recommendation.replace(/```[\s\S]*?```/g, '').trim()
  // Remove HTML tags in the text
  simplified = simplified.replace(/<[^>]+>/g, '')
  // Remove inline code
  simplified = simplified.replace(/`[^`]+`/g, '')
  // Take first sentence or two
  const sentences = simplified.match(/[^.!?]+[.!?]+/g) || [simplified]
  const plain = sentences.slice(0, 2).join(' ').trim()
  return stripTechnicalJargon(plain) || simplified.slice(0, 200)
}

/** Extract code blocks or technical specifics from recommendation */
function extractTechnicalFix(recommendation: string): string | null {
  const codeBlocks = recommendation.match(/```[\s\S]*?```/g)
  if (codeBlocks && codeBlocks.length > 0) {
    return codeBlocks.join('\n\n')
  }
  // If recommendation has HTML-like content or CSS selectors, return it
  if (recommendation.includes('<') && recommendation.includes('>')) {
    return recommendation
  }
  return null
}

// ── Batch processor ──────────────────────────────────────────

/**
 * Process a batch of AnalysisFinding objects and attach communication.
 * This is the main entry point called from process-audit.ts.
 */
export function enrichWithCommunication(
  findings: AnalysisFinding[],
  siteProfile: SiteProfile | null,
): Array<AnalysisFinding & FindingWithCommunication> {
  return findings.map(finding => ({
    ...finding,
    communication: buildCommunicationFromAnalysis(finding, siteProfile),
  }))
}

/**
 * Build communication JSONB for a non-analyzer finding (e.g. from
 * responsive checker, WCAG checker, structured data validator).
 * These findings don't have the AI-generated communication fields.
 */
export function buildCommunicationForGenericFinding(
  finding: GenericFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication {
  return synthesizeCommunication(finding, siteProfile)
}
