// ============================================================
// Fixpath Proprietary Pipeline — Communication Layer
// ============================================================
//
// Builds the dual-layer communication model for each finding:
//   1. Plain-language layer (site owners, marketers, non-technical)
//   2. Technical layer (developers)
//
// Runs AFTER analysis, BEFORE insertion. Processes AnalysisFinding
// objects and attaches a `communication` JSONB payload.
//
// Also applies industry-aware naming rules:
//   - Navigation findings MUST name "menu" or "navigation menu"
//   - Hospitality/venue/event/service sites get explicit nav naming
//   - No generic terms like "interactive elements" or "focus indicators"
//
// For findings that lack AI-generated communication fields (e.g.
// from non-analyzer detection sources like wcag_checker, responsive_
// checker, structured_data), this module synthesizes plain-language
// from the existing title/description/recommendation fields.
// ============================================================

import type { FindingCommunication } from '@/types/database'
import type { AnalysisFinding, SiteProfile } from '../analyzer'

// ── Types ────────────────────────────────────────────────────

export interface FindingWithCommunication {
  communication: FindingCommunication | null
}

/**
 * Minimal shape for findings that come from non-analyzer sources
 * (responsive checker, WCAG checker, structured data, etc.)
 */
export interface GenericFinding {
  title: string
  description: string
  recommendation: string
  estimatedImpact?: string | null
  severity?: string
}

// ── Industry detection ───────────────────────────────────────

/** Industries where visible desktop navigation is especially critical */
const NAV_CRITICAL_INDUSTRIES = [
  'hospitality', 'hotel', 'restaurant', 'venue', 'event',
  'booking', 'service', 'real estate', 'healthcare', 'clinic',
  'spa', 'salon', 'gym', 'fitness', 'travel', 'tourism',
  'fintech', 'banking', 'insurance', 'saas', 'b2b',
  'education', 'university', 'school',
]

function isNavCriticalIndustry(siteProfile: SiteProfile | null): boolean {
  if (!siteProfile?.industryVertical) return true // default: treat as nav-critical
  const vertical = siteProfile.industryVertical.toLowerCase()
  return NAV_CRITICAL_INDUSTRIES.some(ind => vertical.includes(ind))
}

// ── Navigation-specific name enforcement ─────────────────────

/** Terms that indicate a navigation finding but use generic language */
const GENERIC_NAV_TERMS = [
  'interactive elements', 'interactive element',
  'focus indicators', 'focus indicator',
  'discoverability pattern', 'discoverability patterns',
  'mobile paradigm', 'navigation paradigm',
  'hamburger pattern', 'collapsible pattern',
  'responsive navigation pattern',
]

/** Check if a title/description is about navigation but uses generic language */
function isNavFindingWithGenericLanguage(title: string, description: string): boolean {
  const combined = `${title} ${description}`.toLowerCase()
  const isAboutNav = combined.includes('nav') || combined.includes('menu') ||
    combined.includes('hamburger') || combined.includes('sidebar') ||
    combined.includes('header links') || combined.includes('site links')
  const usesGenericTerms = GENERIC_NAV_TERMS.some(term => combined.includes(term))
  return isAboutNav && usesGenericTerms
}

/** Rewrite a generic nav title to be explicit */
function enforceNavNaming(titlePlain: string, description: string): string {
  const lower = titlePlain.toLowerCase()
  // Already explicit about menu/navigation
  if (lower.includes('menu') || lower.includes('navigation menu') || lower.includes('nav menu')) {
    return titlePlain
  }
  // About hidden hamburger on desktop
  if (lower.includes('hamburger') || lower.includes('hidden') || description.toLowerCase().includes('hamburger')) {
    return titlePlain.replace(/interactive elements?/gi, 'navigation menu')
      .replace(/focus indicators?/gi, 'navigation menu')
      .replace(/discoverability patterns?/gi, 'navigation menu')
      .replace(/navigation paradigm/gi, 'navigation menu')
      .replace(/mobile paradigm/gi, 'mobile-style menu')
  }
  // Generic fallback: prepend "Navigation menu: "
  if (isNavFindingWithGenericLanguage(titlePlain, description)) {
    return `Navigation menu: ${titlePlain}`
  }
  return titlePlain
}

// ── Communication builder from AnalysisFinding ───────────────

/**
 * Build FindingCommunication from an AnalysisFinding that was
 * generated by the analyzer (which now outputs communication fields).
 */
export function buildCommunicationFromAnalysis(
  finding: AnalysisFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication | null {
  // If the analyzer provided all mandatory plain-language fields, use them
  if (finding.titlePlain && finding.whatFound && finding.whyMatters && finding.fixPlain) {
    let titlePlain = finding.titlePlain

    // Enforce navigation naming rules
    if (isNavFindingWithGenericLanguage(titlePlain, finding.whatFound || finding.description)) {
      titlePlain = enforceNavNaming(titlePlain, finding.whatFound || finding.description)
    }

    // For nav-critical industries, strengthen nav-related language
    if (isNavCriticalIndustry(siteProfile) && isNavFinding(finding.title, finding.description)) {
      titlePlain = enforceNavNaming(titlePlain, finding.whatFound || finding.description)
    }

    return {
      title_plain: titlePlain,
      what_found: finding.whatFound,
      why_matters: finding.whyMatters,
      technical_note: finding.technicalNote || null,
      fix_plain: finding.fixPlain,
      fix_technical: finding.fixTechnical || null,
    }
  }

  // Fallback: synthesize from existing fields
  return synthesizeCommunication(finding, siteProfile)
}

/** Check if a finding is about navigation */
function isNavFinding(title: string, description: string): boolean {
  const combined = `${title} ${description}`.toLowerCase()
  return combined.includes('nav') || combined.includes('menu') ||
    combined.includes('hamburger') || combined.includes('header links') ||
    combined.includes('site links') || combined.includes('sidebar')
}

// ── Fallback synthesizer ─────────────────────────────────────

/**
 * Synthesize plain-language communication from existing finding fields.
 * Used when:
 *   1. The analyzer didn't return communication fields (shouldn't happen
 *      with the new prompt, but backward-safe)
 *   2. The finding came from a non-analyzer source (WCAG checker,
 *      responsive checker, structured data validator, etc.)
 */
/**
 * Hand-written plain-language copy for the KNOWN deterministic checks
 * (responsive, WCAG, pagespeed). These findings have stable, recognizable
 * titles, so instead of mechanically truncating jargon we emit copy a
 * non-technical person actually understands — and keep the precise technical
 * wording in `technical_note` for developers. Returns null when nothing
 * matches, so the generic synthesizer still handles everything else.
 */
export function plainCopyForDeterministicFinding(
  title: string,
  description: string,
): Pick<FindingCommunication, 'title_plain' | 'what_found' | 'why_matters' | 'fix_plain'> | null {
  const t = `${title} ${description}`.toLowerCase()
  // Pull the quoted element labels the checker listed (e.g. "Product", "Pricing")
  // so we can tell the user WHICH elements, in plain words.
  const examples = Array.from(description.matchAll(/"([^"]{1,40})"/g)).map((m) => m[1]).filter(Boolean)
  const egTail = examples.length ? ` For example: ${examples.slice(0, 3).join(', ')}.` : ''

  const rule = (
    re: RegExp,
    copy: Pick<FindingCommunication, 'title_plain' | 'what_found' | 'why_matters' | 'fix_plain'>,
  ) => (re.test(t) ? copy : null)

  return (
    rule(/touch target|too small to tap|below 44/, {
      title_plain: 'Some buttons and links are too small to tap on a phone',
      what_found: `A few buttons or links are smaller than the size a fingertip needs (about 44×44 pixels), so they're easy to mis-tap on a phone.${egTail}`,
      why_matters: 'People on phones tap the wrong thing or miss it entirely — that frustration costs you clicks and signups.',
      fix_plain: 'Make these buttons and links a little bigger on phones — add padding so the tappable area is at least 44×44 pixels, without changing how they look.',
    }) ||
    rule(/keyboard/, {
      title_plain: "Something on this page can't be used with a keyboard",
      what_found: 'One element only responds to a mouse. People who get around with a keyboard (or assistive tech) can reach it but cannot activate it.',
      why_matters: "Keyboard and screen-reader users get blocked from finishing what they came to do — and it's a legal accessibility risk.",
      fix_plain: 'Make the element keyboard-reachable and add a keyboard action alongside the click, so pressing Enter or Space works too.',
    }) ||
    rule(/non-text content|accessible name|alt text|image description|1\.1\.1/, {
      title_plain: 'An image or icon has no description',
      what_found: 'An image, icon, or graphic has no text description, so screen readers have nothing to read aloud — the content is invisible to blind users.',
      why_matters: "Blind and low-vision visitors miss what the image is saying, and search engines can't read it either.",
      fix_plain: "Add a short description to the image (alt text). If it's purely decorative, mark it as such so screen readers skip it.",
    }) ||
    rule(/contrast|1\.4\.3/, {
      title_plain: 'Some text is too faint to read easily',
      what_found: 'Text and its background are too close in shade, so the words are hard to read — especially in sunlight or for low-vision users.',
      why_matters: 'People squint, skim, or give up reading — and it fails accessibility contrast standards.',
      fix_plain: 'Darken the text or lighten the background until the two have enough contrast to read comfortably.',
    }) ||
    rule(/heading.*(skip|level|label)|skips levels|2\.4\.6/, {
      title_plain: 'Your headings skip levels',
      what_found: 'The page jumps heading levels (for example, a big heading straight to a small sub-sub-heading) instead of stepping down in order.',
      why_matters: 'Screen-reader users rely on heading order to navigate; skipping levels makes the page confusing to move through.',
      fix_plain: 'Use headings in order (H1, then H2, then H3) without skipping a level.',
    }) ||
    rule(/fixed width|exceeding.*viewport|horizontal (scroll|overflow)|wider than/, {
      title_plain: 'Part of the page is wider than a phone screen',
      what_found: `Something on the page is set to a fixed width that's wider than a phone, so it spills off the edge and creates sideways scrolling.${egTail}`,
      why_matters: 'Sideways scrolling on mobile is the #1 thing that makes a site feel broken — visitors bounce.',
      fix_plain: 'Let the element shrink to fit the screen (use a flexible/percentage width or a max-width of 100%) instead of a fixed pixel width.',
    }) ||
    rule(/media element|image.*overflow|video.*overflow/, {
      title_plain: 'An image or video runs off the side of the screen',
      what_found: 'An image, video, or embed is wider than the screen, so it gets cut off or causes sideways scrolling on smaller devices.',
      why_matters: 'Cut-off media looks broken and pushes the layout sideways on phones.',
      fix_plain: 'Make media scale to its container — set its maximum width to 100% so it always fits the screen.',
    }) ||
    rule(/tightly packed|breathing room|content.*dense|spacing between/, {
      title_plain: 'Your content is crammed together on phones',
      what_found: 'On phones, sections and paragraphs sit almost on top of each other with little space between them, so the page is hard to scan.',
      why_matters: 'Dense walls of text are tiring to read on a small screen, so people skim and miss your message.',
      fix_plain: 'Add more breathing room on phones — a bit more space below paragraphs and between sections.',
    }) ||
    rule(/lines exceed|line length|characters? per line|75 character/, {
      title_plain: 'Lines of text run too long to read comfortably',
      what_found: 'Some paragraphs stretch very wide, so each line has too many characters and the eye loses its place jumping back to the start.',
      why_matters: 'Over-long lines slow reading and tire the eyes, so people read less of your page.',
      fix_plain: 'Cap the width of text blocks (or add side padding) so lines stay in a comfortable 45–75 character range.',
    }) ||
    rule(/text.*(below|smaller).*1[024]px|too small to read|font size/, {
      title_plain: 'Some text is too small to read on phones',
      what_found: `Some text renders very small on phones — below the size that's comfortable to read without zooming.${egTail}`,
      why_matters: 'Tiny text makes people pinch-zoom or give up — a real drop-off on mobile.',
      fix_plain: 'Bump the smallest text up so body copy is comfortable to read on a phone (around 16px).',
    }) ||
    rule(/navigation.*(hidden|adapt)|hamburger|menu.*(hidden|mobile)/, {
      title_plain: "Your main menu isn't shown the right way on this screen",
      what_found: "On this screen size, your primary menu is either hidden behind a toggle when it shouldn't be, or not adapted for the device.",
      why_matters: 'If people can\'t see where to go, they don\'t explore — navigation problems quietly kill engagement.',
      fix_plain: 'Show your main links directly on bigger screens, and use a clean menu button on phones.',
    }) ||
    rule(/multiple redirect|redirects detected/, {
      title_plain: 'Visitors get bounced through extra web addresses before your page loads',
      what_found: 'Reaching this page sends the browser through several redirects, each one a round-trip that adds delay before anything appears.',
      why_matters: "Every redirect is dead waiting time — painful on mobile networks and a small but real hit to speed and SEO.",
      fix_plain: 'Point your links straight at the final web address so the browser loads the page in one step.',
    }) ||
    rule(/unused javascript|unused js/, {
      title_plain: 'The page loads code it never uses',
      what_found: 'The page downloads and processes JavaScript that never runs here, spending the visitor\'s bandwidth and phone battery for nothing.',
      why_matters: 'That dead code delays when the page becomes tappable — it looks ready before it actually is.',
      fix_plain: 'Trim or split your scripts so each page only loads the code it actually needs.',
    }) ||
    rule(/missing viewport meta/, {
      title_plain: 'The page is missing its mobile setup tag',
      what_found: 'The page has no viewport tag, so phones render it at desktop width and shrink it down — text becomes tiny and tapping is hard.',
      why_matters: "Without it the entire mobile experience is broken from the first second.",
      fix_plain: 'Add the standard mobile viewport tag to the page so it sizes correctly on phones.',
    }) ||
    null
  )
}

export function synthesizeCommunication(
  finding: GenericFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication {
  const title = finding.title
  const desc = finding.description
  const rec = finding.recommendation
  const impact = finding.estimatedImpact || ''

  // First, try the curated plain-language copy for known deterministic checks.
  // Keep the original technical wording in technical_note for developers.
  const curated = plainCopyForDeterministicFinding(title, desc)
  if (curated) {
    return {
      title_plain: isNavFinding(title, desc) ? enforceNavNaming(curated.title_plain, desc) : curated.title_plain,
      what_found: curated.what_found,
      why_matters: curated.why_matters,
      technical_note: desc !== curated.what_found ? `${desc}${rec ? `\n\nRecommended: ${rec}` : ''}` : (rec || null),
      fix_plain: curated.fix_plain,
      fix_technical: extractTechnicalFix(rec),
    }
  }

  // Build a plain title — strip technical jargon if detected
  let titlePlain = stripTechnicalJargon(title)

  // Enforce nav naming
  if (isNavFinding(title, desc)) {
    titlePlain = enforceNavNaming(titlePlain, desc)
  }

  // Build "what we found" — first 2 sentences of description, simplified
  const whatFound = simplifyDescription(desc)

  // Build "why it matters" — use estimated_impact or extract from description
  const whyMatters = impact
    ? simplifyImpact(impact)
    : extractWhyFromDescription(desc)

  // Build plain fix — strip code blocks and technical details from recommendation
  const fixPlain = simplifyRecommendation(rec)

  // Technical note — keep full recommendation as-is
  const technicalNote = rec.length > fixPlain.length ? rec : null

  // Technical fix — extract code blocks or technical specifics
  const fixTechnical = extractTechnicalFix(rec)

  return {
    title_plain: titlePlain,
    what_found: whatFound,
    why_matters: whyMatters,
    technical_note: technicalNote,
    fix_plain: fixPlain,
    fix_technical: fixTechnical,
  }
}

// ── Text transformation helpers ──────────────────────────────

/** Common technical terms → plain-language replacements */
const JARGON_MAP: Array<[RegExp, string]> = [
  [/\bCTA\b/gi, 'call-to-action button'],
  [/\bDOM\b/gi, 'page structure'],
  [/\bARIA\b/gi, 'accessibility'],
  [/\bJSON-LD\b/gi, 'structured data'],
  [/\bSEO\b/gi, 'search visibility'],
  [/\balt text\b/gi, 'image description'],
  [/\balt attribute\b/gi, 'image description'],
  [/\bmeta description\b/gi, 'search result description'],
  [/\bviewport\b/gi, 'screen size'],
  [/\bCSS\b/g, 'styling'],
  [/\bHTML\b/g, 'page code'],
  [/\bsemantic\b/gi, 'meaningful'],
  [/\bresponsive\b/gi, 'mobile-friendly'],
  [/\breadability score\b/gi, 'readability'],
  // 2026-06-12: the old rule here rewrote 'WCAG 2.4.7' into mangled text
  // ('accessibility standards.7') by half-eating the criterion number.
  // WCAG criterion IDs are CITABLE EVIDENCE — a trust product keeps them.
  // Only the bare level suffix is softened (e.g. 'WCAG AA' → 'accessibility
  // standards (WCAG AA)').
  [/\bWCAG\s+(AA|AAA)\b/g, 'accessibility standards (WCAG $1)'],
  [/\bheading hierarchy\b/gi, 'heading structure'],
  [/\bcanonical URL\b/gi, 'preferred web address'],
  [/\bstructured data\b/gi, 'machine-readable information'],
  [/\brender\b/gi, 'display'],
  [/\blazy load(ing)?\b/gi, 'delayed loading'],
]

/** Shield abbreviations from the sentence splitter (e.g., i.e., etc., vs., approx.) */
const ABBREV_SHIELD: Array<[RegExp, string]> = [
  [/\be\.\s?g\./gi, '\u0001EG\u0001'],
  [/\bi\.\s?e\./gi, '\u0001IE\u0001'],
  [/\betc\./gi, '\u0001ETC\u0001'],
  [/\bvs\./gi, '\u0001VS\u0001'],
  [/\bapprox\./gi, '\u0001APPROX\u0001'],
]
function shieldAbbreviations(text: string): string {
  let out = text
  for (const [re, token] of ABBREV_SHIELD) out = out.replace(re, token)
  // Numbered-list markers ('1.' after a colon or newline) are not
  // sentence boundaries — the splitter was truncating recommendations
  // at 'The link should: 1.'
  out = out.replace(/([:\n]\s*)(\d{1,2})\./g, '$1$2\u0001DOT\u0001')
  // Dotted numeric references (WCAG 2.4.7, version 1.2, §3.3.2) — a period
  // between digits is never a sentence boundary. This was the source of
  // '[WCAG 2. 4. 7]' in customer-facing text: the splitter cut at every
  // digit-period and re-joined with spaces.
  out = out.replace(/(\d)\.(?=\d)/g, '$1\u0001DOT\u0001')
  return out
}
function unshieldAbbreviations(text: string): string {
  return text
    .replace(/\u0001DOT\u0001/g, '.')
    .replace(/\u0001EG\u0001/g, 'e.g.')
    .replace(/\u0001IE\u0001/g, 'i.e.')
    .replace(/\u0001ETC\u0001/g, 'etc.')
    .replace(/\u0001VS\u0001/g, 'vs.')
    .replace(/\u0001APPROX\u0001/g, 'approx.')
}

function stripTechnicalJargon(text: string): string {
  let result = text
  for (const [pattern, replacement] of JARGON_MAP) {
    result = result.replace(pattern, replacement)
  }
  return result
}

/** Extract the first 2-3 sentences as a simplified description */
function simplifyDescription(description: string): string {
  // Remove code blocks
  let simplified = description.replace(/```[\s\S]*?```/g, '').trim()
  // Remove inline code
  simplified = simplified.replace(/`[^`]+`/g, (match) => {
    const inner = match.slice(1, -1)
    // If it looks like a CSS selector or code, replace with description
    if (inner.includes('.') || inner.includes('#') || inner.includes('<') || inner.includes('>')) {
      return 'the element'
    }
    return inner
  })
  // Take first 2-3 sentences
  const shielded = shieldAbbreviations(simplified)
  const sentences = shielded.match(/[^.!?]+[.!?]+/g) || [shielded]
  const plain = unshieldAbbreviations(sentences.slice(0, 3).join(' ').trim())
  return stripTechnicalJargon(plain) || simplified.slice(0, 300)
}

/** Simplify estimated_impact to plain language */
function simplifyImpact(impact: string): string {
  return stripTechnicalJargon(impact)
}

/** Extract "why it matters" from description when no impact is available */
function extractWhyFromDescription(description: string): string {
  const lower = description.toLowerCase()
  // Look for impact-related sentences
  const impactIndicators = [
    'this means', 'this causes', 'this results in', 'as a result',
    'users will', 'visitors will', 'customers will',
    'this makes it', 'this prevents', 'this reduces',
    'hurts', 'damages', 'weakens', 'confuses',
    'lost', 'missing', 'broken',
  ]
  const sentences = (shieldAbbreviations(description).match(/[^.!?]+[.!?]+/g) || []).map(unshieldAbbreviations)
  for (const sentence of sentences) {
    const sentenceLower = sentence.toLowerCase()
    if (impactIndicators.some(ind => sentenceLower.includes(ind))) {
      return stripTechnicalJargon(sentence.trim())
    }
  }
  // Fallback: generic impact statement
  return 'This issue may affect how visitors experience and interact with your site.'
}

/** Strip code blocks and technical specifics from recommendation */
function simplifyRecommendation(recommendation: string): string {
  // Remove code blocks
  let simplified = recommendation.replace(/```[\s\S]*?```/g, '').trim()
  // HTML tag mentions: keep the tag NAME as text (2026-06-12 — deleting
  // them produced "Add a skip link in the page's ." when the source said
  // "in the page's <body>"). Closing tags drop; opening tags become the
  // quoted tag name.
  simplified = simplified.replace(/<\/[a-z][a-z0-9-]*\s*>/gi, '')
  simplified = simplified.replace(/<([a-z][a-z0-9-]*)\b[^>]*>/gi, "'$1'")
  // Inline code: KEEP the inner text (2026-06-12 — deleting it produced
  // recommendations ending at '(e.g.' because the example WAS the code span)
  simplified = simplified.replace(/`([^`]+)`/g, '$1')
  // Take first sentence or two
  const shieldedRec = shieldAbbreviations(simplified)
  const sentences = (shieldedRec.match(/[^.!?]+[.!?]+/g) || [shieldedRec]).map(unshieldAbbreviations)
  const plain = sentences.slice(0, 2).join(' ').trim()
  return stripTechnicalJargon(plain) || simplified.slice(0, 200)
}

/** Extract code blocks or technical specifics from recommendation */
function extractTechnicalFix(recommendation: string): string | null {
  const codeBlocks = recommendation.match(/```[\s\S]*?```/g)
  if (codeBlocks && codeBlocks.length > 0) {
    return codeBlocks.join('\n\n')
  }
  // If recommendation has HTML-like content or CSS selectors, return it
  if (recommendation.includes('<') && recommendation.includes('>')) {
    return recommendation
  }
  return null
}

// ── Batch processor ──────────────────────────────────────────

/**
 * Process a batch of AnalysisFinding objects and attach communication.
 * This is the main entry point called from process-audit.ts.
 */
export function enrichWithCommunication(
  findings: AnalysisFinding[],
  siteProfile: SiteProfile | null,
): Array<AnalysisFinding & FindingWithCommunication> {
  return findings.map(finding => ({
    ...finding,
    communication: buildCommunicationFromAnalysis(finding, siteProfile),
  }))
}

/**
 * Build communication JSONB for a non-analyzer finding (e.g. from
 * responsive checker, WCAG checker, structured data validator).
 * These findings don't have the AI-generated communication fields.
 */
export function buildCommunicationForGenericFinding(
  finding: GenericFinding,
  siteProfile: SiteProfile | null,
): FindingCommunication {
  return synthesizeCommunication(finding, siteProfile)
}
