// ============================================================
// ClearUX Proprietary Pipeline — Finding Lifecycle Debug Trace
// ============================================================
//
// PURPOSE:
// Track every finding from generation through each filter stage,
// recording exactly what happened at each step and why. This makes
// it possible to debug "why was this finding dropped?" or "why did
// this finding survive?" without re-running the audit.
//
// HOW IT WORKS:
// 1. At each pipeline stage (dedup, speculative filter, relevance
//    scorer, minimum findings), call addTraceEvent() with the
//    finding ID, stage name, and action taken.
// 2. After the pipeline completes, call summarizeTrace() to get
//    a human-readable summary of all findings' journeys.
// 3. The trace is stored in-memory per audit run and optionally
//    logged to console or audit_log.
//
// INTEGRATION:
// - Feature-flagged via FINDING_TRACE_ENABLED env var
// - Zero overhead when disabled (all calls short-circuit)
// - No DB writes — in-memory only, logged to console
// ============================================================

export type TraceAction = 'generated' | 'kept' | 'merged' | 'dropped' | 'softened' | 'injected'

export interface TraceEvent {
  /** Pipeline stage that acted on the finding */
  stage: string
  /** What happened */
  action: TraceAction
  /** Human-readable reason */
  reason: string
  /** Timestamp */
  timestamp: number
}

export interface FindingTrace {
  /** Finding ID (or temporary ID if not yet persisted) */
  findingId: string
  /** Short title for display */
  title: string
  /** Category index */
  categoryIndex: number
  /** Severity at generation time */
  severity: string
  /** Ordered list of events in this finding's lifecycle */
  events: TraceEvent[]
  /** Final outcome */
  finalStatus: 'survived' | 'dropped' | 'merged' | 'unknown'
}

/**
 * In-memory trace store for a single audit run.
 * Create one per audit, pass it through the pipeline.
 */
export class FindingTracer {
  private traces: Map<string, FindingTrace> = new Map()
  private enabled: boolean

  constructor(enabled?: boolean) {
    this.enabled = enabled ?? (process.env.FINDING_TRACE_ENABLED === 'true' || process.env.FINDING_TRACE_ENABLED === '1')
  }

  /** Check if tracing is active */
  get isEnabled(): boolean {
    return this.enabled
  }

  /**
   * Register a newly generated finding.
   */
  registerFinding(findingId: string, title: string, categoryIndex: number, severity: string): void {
    if (!this.enabled) return
    this.traces.set(findingId, {
      findingId,
      title: title.slice(0, 80),
      categoryIndex,
      severity,
      events: [{
        stage: 'generation',
        action: 'generated',
        reason: `Generated by analyzeCategory() for category ${categoryIndex}`,
        timestamp: Date.now(),
      }],
      finalStatus: 'unknown',
    })
  }

  /**
   * Record an event in a finding's lifecycle.
   */
  addEvent(findingId: string, stage: string, action: TraceAction, reason: string): void {
    if (!this.enabled) return
    const trace = this.traces.get(findingId)
    if (!trace) {
      // Finding wasn't registered — create a minimal trace
      this.traces.set(findingId, {
        findingId,
        title: '(unregistered)',
        categoryIndex: -1,
        severity: 'unknown',
        events: [{
          stage,
          action,
          reason,
          timestamp: Date.now(),
        }],
        finalStatus: 'unknown',
      })
      return
    }
    trace.events.push({ stage, action, reason, timestamp: Date.now() })

    // Update final status based on action
    if (action === 'dropped') trace.finalStatus = 'dropped'
    else if (action === 'merged') trace.finalStatus = 'merged'
  }

  /**
   * Batch-register dedup results.
   */
  recordDedupResults(duplicateIds: string[], reason: string = 'Identified as duplicate by dedup engine'): void {
    if (!this.enabled) return
    for (const id of duplicateIds) {
      this.addEvent(id, 'dedup', 'merged', reason)
    }
  }

  /**
   * Batch-register speculative filter results.
   */
  recordSpeculativeFilterResults(speculativeIds: string[], reason: string = 'Matched speculative/unverifiable pattern'): void {
    if (!this.enabled) return
    for (const id of speculativeIds) {
      this.addEvent(id, 'speculative-filter', 'dropped', reason)
    }
  }

  /**
   * Batch-register relevance scorer results.
   */
  recordRelevanceResults(droppedIds: string[], reason: string = 'Below relevance threshold'): void {
    if (!this.enabled) return
    for (const id of droppedIds) {
      this.addEvent(id, 'relevance-scorer', 'dropped', reason)
    }
  }

  /**
   * Mark all remaining findings as survived.
   */
  markSurvivors(survivingIds: Set<string>): void {
    if (!this.enabled) return
    for (const [id, trace] of this.traces) {
      if (survivingIds.has(id) && trace.finalStatus === 'unknown') {
        trace.finalStatus = 'survived'
        trace.events.push({
          stage: 'final',
          action: 'kept',
          reason: 'Passed all pipeline filters — included in report',
          timestamp: Date.now(),
        })
      }
    }
  }

  /**
   * Get a summary of the trace for logging.
   */
  summarize(): {
    total: number
    survived: number
    dropped: number
    merged: number
    droppedByStage: Record<string, number>
    traces: FindingTrace[]
  } {
    const traces = Array.from(this.traces.values())
    const survived = traces.filter(t => t.finalStatus === 'survived').length
    const dropped = traces.filter(t => t.finalStatus === 'dropped').length
    const merged = traces.filter(t => t.finalStatus === 'merged').length

    const droppedByStage: Record<string, number> = {}
    for (const trace of traces) {
      if (trace.finalStatus === 'dropped' || trace.finalStatus === 'merged') {
        const dropEvent = trace.events.find(e => e.action === 'dropped' || e.action === 'merged')
        if (dropEvent) {
          droppedByStage[dropEvent.stage] = (droppedByStage[dropEvent.stage] || 0) + 1
        }
      }
    }

    return { total: traces.length, survived, dropped, merged, droppedByStage, traces }
  }

  /**
   * Log the full trace summary to console.
   */
  logSummary(auditId: string): void {
    if (!this.enabled) return
    const summary = this.summarize()
    console.log(`\n[finding-trace] ═══════════════════════════════════════`)
    console.log(`[finding-trace] Audit: ${auditId}`)
    console.log(`[finding-trace] Total generated: ${summary.total}`)
    console.log(`[finding-trace] Survived: ${summary.survived}`)
    console.log(`[finding-trace] Dropped: ${summary.dropped}`)
    console.log(`[finding-trace] Merged:  ${summary.merged}`)

    if (Object.keys(summary.droppedByStage).length > 0) {
      console.log(`[finding-trace] ─── Dropped by stage ───`)
      for (const [stage, count] of Object.entries(summary.droppedByStage)) {
        console.log(`[finding-trace]   ${stage}: ${count}`)
      }
    }

    // Log individual finding journeys for dropped/merged findings
    const removed = summary.traces.filter(t => t.finalStatus !== 'survived' && t.finalStatus !== 'unknown')
    if (removed.length > 0) {
      console.log(`[finding-trace] ─── Removed findings ───`)
      for (const trace of removed) {
        const journey = trace.events.map(e => `${e.stage}:${e.action}`).join(' → ')
        console.log(`[finding-trace]   [${trace.finalStatus}] cat=${trace.categoryIndex} sev=${trace.severity} "${trace.title}" | ${journey}`)
      }
    }

    console.log(`[finding-trace] ═══════════════════════════════════════\n`)
  }

  /**
   * Get the raw trace data (for storing in audit metadata if needed).
   */
  getTraces(): FindingTrace[] {
    return Array.from(this.traces.values())
  }
}

/**
 * Create a no-op tracer that does nothing (zero overhead).
 * Used when tracing is disabled.
 */
export function createTracer(auditId?: string): FindingTracer {
  return new FindingTracer()
}
