import type { Metadata } from 'next'
import { MarketingBody } from '@/components/marketing/MarketingBody'
import { Nav } from '@/components/marketing/Nav'
import { Footer } from '@/components/marketing/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Fixpath terms of service — the rules and guidelines for using our platform.',
}

export default function TermsPage() {
  return (
    <MarketingBody>
      <Nav />
      <main>
        <section className="py-[80px] border-b border-rule max-sm:py-14">
          <div className="max-w-[760px] mx-auto px-8 max-sm:px-5">
            <span className="font-mono text-[11px] tracking-[0.1em] uppercase text-signal mb-4 block">Legal</span>
            <h1 className="font-serif font-normal text-ink leading-[0.96] tracking-[-0.02em] mb-3" style={{ fontSize: 'clamp(36px, 5vw, 56px)' }}>
              Terms of service
            </h1>
            <p className="font-mono text-[11px] text-m-muted tracking-[0.06em] uppercase">Last updated: April 2026</p>
          </div>
        </section>

        <section className="py-[60px]">
          <div className="max-w-[760px] mx-auto px-8 max-sm:px-5 space-y-8 font-sans text-[15px] text-ink-2 leading-[1.7]">
            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">1. Acceptance of terms</h2>
              <p>By creating an account or using Fixpath, you agree to these Terms of Service. If you do not agree, please do not use the platform. We may update these terms from time to time — continued use after changes constitutes acceptance.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">2. The service</h2>
              <p>Fixpath provides AI-powered UX audits of publicly accessible websites. You submit a URL, our engine crawls and analyses the site, and we deliver a report with findings and recommendations. Reports are generated by AI and should be used as guidance — they do not constitute professional consulting advice.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">3. Accounts &amp; credits</h2>
              <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your credentials. Credits are non-refundable, do not expire, and are tied to your account. Each audit consumes one or more credits depending on the plan selected.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">4. Acceptable use</h2>
              <p>You may only audit URLs you own or have permission to audit. You must not use Fixpath to scan websites for the purpose of exploiting vulnerabilities, harassing site owners, or any unlawful activity. We reserve the right to suspend accounts that violate these terms.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">5. Intellectual property</h2>
              <p>Fixpath, its branding, and underlying technology are our intellectual property. Reports generated for your audits belong to you — you may share, distribute, or use them as you see fit. You retain ownership of any data you submit to the platform.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">6. Limitations &amp; disclaimers</h2>
              <p>Fixpath reports are AI-generated analysis and are provided &ldquo;as is.&rdquo; We do not guarantee that implementing recommendations will produce specific results. We are not liable for any direct, indirect, or consequential damages arising from your use of the service. Our maximum liability is limited to the amount you paid for credits in the preceding 12 months.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">7. Termination</h2>
              <p>You may delete your account at any time. We may suspend or terminate your account if you violate these terms. Upon termination, your data will be deleted within 30 days unless required by law to retain it.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">8. Governing law</h2>
              <p>These terms are governed by and construed in accordance with applicable law. Any disputes will be resolved through good-faith negotiation before pursuing formal legal remedies.</p>
            </div>

            <div>
              <h2 className="font-sans font-medium text-[17px] text-ink mb-2">9. Contact</h2>
              <p>Questions about these terms? Contact us at <a href="mailto:support@fixpath.ai" className="text-ink font-medium underline decoration-signal decoration-2 underline-offset-2 hover:text-signal transition-colors">support@fixpath.ai</a>.</p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </MarketingBody>
  )
}
