// ============================================================
// Fixpath AI Interrogation — Canonical Question Library
// ============================================================
// Durable, reusable questions organized by family, category,
// region, and audience type. The shortlist generator scores and
// ranks these per-workspace to replace the old hardcoded 3-5
// generic probe questions.
//
// {business} is the interpolation placeholder — replaced at
// runtime with the workspace's brand name or domain.
// ============================================================

/* ── Question families ──────────────────────────────────────── */

export const QUESTION_FAMILIES = [
  'general_discovery',
  'trust_credibility',
  'differentiation',
  'quality_perception',
  'pricing_value',
  'booking_buying_readiness',
  'local_relevance',
  'service_clarity',
  'reputation_social_proof',
  'premium_budget_perception',
  'audience_fit',
  'brand_tone_personality',
] as const

export type QuestionFamily = (typeof QUESTION_FAMILIES)[number]

/* ── Category constants ─────────────────────────────────────── */

export const CATEGORIES = [
  'hospitality',
  'restaurant',
  'saas',
  'healthcare',
  'ecommerce',
  'education',
  'finance',
  'legal',
  'real_estate',
  'automotive',
  'beauty_wellness',
  'fitness',
  'travel',
  'media',
  'nonprofit',
  'professional_services',
  'retail',
  'food_beverage',
  'entertainment',
  'technology',
] as const

export type Category = (typeof CATEGORIES)[number]

/* ── Question definition ────────────────────────────────────── */

export interface QuestionDef {
  id: string
  questionTemplate: string
  family: QuestionFamily
  category: Category | null
  subcategory: string | null
  region: string | null
  language: string
  audienceType: string | null
  intentTags: string[]
  priorityScore: number
  followupIds: string[]
}

/* ── Canonical questions ────────────────────────────────────── */

export const CANONICAL_QUESTIONS: QuestionDef[] = [

  // ────────────────────────────────────────────────────────────
  // FAMILY: general_discovery
  // ────────────────────────────────────────────────────────────

  {
    id: 'gd-001',
    questionTemplate: 'What is {business}?',
    family: 'general_discovery',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['discovery', 'brand_awareness'],
    priorityScore: 95,
    followupIds: ['gd-002', 'tc-001'],
  },
  {
    id: 'gd-002',
    questionTemplate: 'What does {business} do?',
    family: 'general_discovery',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['discovery', 'service_understanding'],
    priorityScore: 90,
    followupIds: ['sc-001', 'df-001'],
  },
  {
    id: 'gd-003',
    questionTemplate: 'Who founded {business} and what is their story?',
    family: 'general_discovery',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['discovery', 'brand_story', 'leadership'],
    priorityScore: 55,
    followupIds: ['btp-001'],
  },
  {
    id: 'gd-004',
    questionTemplate: 'What products or services does {business} offer?',
    family: 'general_discovery',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['discovery', 'product_catalog'],
    priorityScore: 85,
    followupIds: ['pv-001', 'sc-001'],
  },
  {
    id: 'gd-005',
    questionTemplate: 'Is {business} still operating?',
    family: 'general_discovery',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['discovery', 'status_check'],
    priorityScore: 60,
    followupIds: ['gd-001'],
  },
  {
    id: 'gd-006',
    questionTemplate: 'What integrations does {business} support?',
    family: 'general_discovery',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['discovery', 'integrations', 'technical'],
    priorityScore: 80,
    followupIds: ['sc-006', 'df-006'],
  },
  {
    id: 'gd-007',
    questionTemplate: 'What specialties does {business} offer?',
    family: 'general_discovery',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['discovery', 'specialties', 'medical'],
    priorityScore: 82,
    followupIds: ['sc-007', 'tc-007'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: trust_credibility
  // ────────────────────────────────────────────────────────────

  {
    id: 'tc-001',
    questionTemplate: 'Is {business} trustworthy?',
    family: 'trust_credibility',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['trust', 'credibility', 'safety'],
    priorityScore: 95,
    followupIds: ['rsp-001', 'tc-002'],
  },
  {
    id: 'tc-002',
    questionTemplate: 'Is {business} legit or a scam?',
    family: 'trust_credibility',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['trust', 'scam_check', 'safety'],
    priorityScore: 90,
    followupIds: ['rsp-001', 'rsp-002'],
  },
  {
    id: 'tc-003',
    questionTemplate: 'Is {business} a trusted clinic?',
    family: 'trust_credibility',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['trust', 'medical_credibility', 'safety'],
    priorityScore: 88,
    followupIds: ['rsp-003', 'qp-005'],
  },
  {
    id: 'tc-004',
    questionTemplate: 'Does {business} have proper licensing and certifications?',
    family: 'trust_credibility',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['trust', 'licensing', 'credentials'],
    priorityScore: 70,
    followupIds: ['tc-001'],
  },
  {
    id: 'tc-005',
    questionTemplate: 'Is it safe to buy from {business} online?',
    family: 'trust_credibility',
    category: 'ecommerce',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['trust', 'online_safety', 'ecommerce'],
    priorityScore: 88,
    followupIds: ['rsp-001', 'bbr-005'],
  },
  {
    id: 'tc-006',
    questionTemplate: 'Is {business} a reliable hotel?',
    family: 'trust_credibility',
    category: 'hospitality',
    subcategory: 'hotel',
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['trust', 'reliability', 'hospitality'],
    priorityScore: 85,
    followupIds: ['rsp-004', 'qp-003'],
  },
  {
    id: 'tc-007',
    questionTemplate: 'Are the doctors at {business} board-certified?',
    family: 'trust_credibility',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['trust', 'credentials', 'medical'],
    priorityScore: 78,
    followupIds: ['tc-003', 'gd-007'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: differentiation
  // ────────────────────────────────────────────────────────────

  {
    id: 'df-001',
    questionTemplate: 'What makes {business} different from competitors?',
    family: 'differentiation',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['comparison', 'unique_value', 'competitive'],
    priorityScore: 90,
    followupIds: ['df-002', 'qp-001'],
  },
  {
    id: 'df-002',
    questionTemplate: 'What are the pros and cons of {business}?',
    family: 'differentiation',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['comparison', 'evaluation', 'pros_cons'],
    priorityScore: 88,
    followupIds: ['pv-001', 'rsp-001'],
  },
  {
    id: 'df-003',
    questionTemplate: 'How does {business} compare to other restaurants in the area?',
    family: 'differentiation',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['comparison', 'local', 'restaurant'],
    priorityScore: 82,
    followupIds: ['lr-003', 'qp-002'],
  },
  {
    id: 'df-004',
    questionTemplate: 'Is {business} better than its competitors for enterprise use?',
    family: 'differentiation',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'enterprise',
    intentTags: ['comparison', 'enterprise', 'competitive'],
    priorityScore: 80,
    followupIds: ['af-004', 'pv-006'],
  },
  {
    id: 'df-005',
    questionTemplate: 'What are the best alternatives to {business}?',
    family: 'differentiation',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['comparison', 'alternatives', 'competitive'],
    priorityScore: 92,
    followupIds: ['df-001', 'pv-001'],
  },
  {
    id: 'df-006',
    questionTemplate: 'How does {business} compare to [competitor type] for small teams?',
    family: 'differentiation',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['comparison', 'small_business', 'competitive'],
    priorityScore: 78,
    followupIds: ['pv-006', 'af-002'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: quality_perception
  // ────────────────────────────────────────────────────────────

  {
    id: 'qp-001',
    questionTemplate: 'Is {business} any good?',
    family: 'quality_perception',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['quality', 'evaluation', 'general'],
    priorityScore: 90,
    followupIds: ['rsp-001', 'df-002'],
  },
  {
    id: 'qp-002',
    questionTemplate: 'How is the food at {business}?',
    family: 'quality_perception',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['quality', 'food', 'dining'],
    priorityScore: 88,
    followupIds: ['qp-004', 'pv-003'],
  },
  {
    id: 'qp-003',
    questionTemplate: "What's the ambiance like at {business}?",
    family: 'quality_perception',
    category: 'hospitality',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['quality', 'ambiance', 'experience'],
    priorityScore: 75,
    followupIds: ['tc-006', 'bbr-003'],
  },
  {
    id: 'qp-004',
    questionTemplate: 'Does {business} use fresh or high-quality ingredients?',
    family: 'quality_perception',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['quality', 'ingredients', 'food'],
    priorityScore: 70,
    followupIds: ['qp-002'],
  },
  {
    id: 'qp-005',
    questionTemplate: 'What is the patient experience like at {business}?',
    family: 'quality_perception',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['quality', 'patient_experience', 'medical'],
    priorityScore: 82,
    followupIds: ['rsp-003', 'tc-003'],
  },
  {
    id: 'qp-006',
    questionTemplate: 'How reliable is the {business} platform?',
    family: 'quality_perception',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['quality', 'reliability', 'uptime'],
    priorityScore: 80,
    followupIds: ['tc-001', 'df-004'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: pricing_value
  // ────────────────────────────────────────────────────────────

  {
    id: 'pv-001',
    questionTemplate: 'How much does {business} cost?',
    family: 'pricing_value',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['pricing', 'cost', 'budget'],
    priorityScore: 90,
    followupIds: ['pv-002', 'pbp-001'],
  },
  {
    id: 'pv-002',
    questionTemplate: 'Is {business} worth the price?',
    family: 'pricing_value',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['pricing', 'value', 'worth'],
    priorityScore: 88,
    followupIds: ['qp-001', 'df-002'],
  },
  {
    id: 'pv-003',
    questionTemplate: 'Is {business} expensive for what you get?',
    family: 'pricing_value',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['pricing', 'value', 'dining'],
    priorityScore: 78,
    followupIds: ['pv-002', 'qp-002'],
  },
  {
    id: 'pv-004',
    questionTemplate: 'Does {business} offer a free trial or free plan?',
    family: 'pricing_value',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['pricing', 'free_trial', 'onboarding'],
    priorityScore: 85,
    followupIds: ['pv-006', 'bbr-006'],
  },
  {
    id: 'pv-005',
    questionTemplate: 'Does {business} accept insurance?',
    family: 'pricing_value',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['pricing', 'insurance', 'medical'],
    priorityScore: 85,
    followupIds: ['pv-001', 'bbr-007'],
  },
  {
    id: 'pv-006',
    questionTemplate: 'What are the pricing tiers for {business}?',
    family: 'pricing_value',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['pricing', 'tiers', 'plans'],
    priorityScore: 82,
    followupIds: ['pv-004', 'df-006'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: booking_buying_readiness
  // ────────────────────────────────────────────────────────────

  {
    id: 'bbr-001',
    questionTemplate: 'How do I get started with {business}?',
    family: 'booking_buying_readiness',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['booking', 'onboarding', 'getting_started'],
    priorityScore: 85,
    followupIds: ['pv-001', 'sc-001'],
  },
  {
    id: 'bbr-002',
    questionTemplate: 'Can I book a room at {business} right now?',
    family: 'booking_buying_readiness',
    category: 'hospitality',
    subcategory: 'hotel',
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['booking', 'availability', 'hotel'],
    priorityScore: 88,
    followupIds: ['pv-001', 'qp-003'],
  },
  {
    id: 'bbr-003',
    questionTemplate: 'Is {business} good for private events?',
    family: 'booking_buying_readiness',
    category: 'hospitality',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['booking', 'events', 'private_dining'],
    priorityScore: 72,
    followupIds: ['qp-003', 'pv-001'],
  },
  {
    id: 'bbr-004',
    questionTemplate: 'Does {business} take reservations?',
    family: 'booking_buying_readiness',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['booking', 'reservations', 'dining'],
    priorityScore: 80,
    followupIds: ['lr-003', 'sc-003'],
  },
  {
    id: 'bbr-005',
    questionTemplate: 'What is the return policy at {business}?',
    family: 'booking_buying_readiness',
    category: 'ecommerce',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['buying', 'returns', 'policy'],
    priorityScore: 82,
    followupIds: ['tc-005', 'sc-005'],
  },
  {
    id: 'bbr-006',
    questionTemplate: 'How do I sign up for {business}?',
    family: 'booking_buying_readiness',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['booking', 'signup', 'onboarding'],
    priorityScore: 78,
    followupIds: ['pv-004', 'sc-006'],
  },
  {
    id: 'bbr-007',
    questionTemplate: 'How do I book an appointment at {business}?',
    family: 'booking_buying_readiness',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['booking', 'appointment', 'medical'],
    priorityScore: 85,
    followupIds: ['pv-005', 'sc-007'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: local_relevance
  // ────────────────────────────────────────────────────────────

  {
    id: 'lr-001',
    questionTemplate: 'Where is {business} located?',
    family: 'local_relevance',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['local', 'location', 'directions'],
    priorityScore: 80,
    followupIds: ['lr-002', 'sc-002'],
  },
  {
    id: 'lr-002',
    questionTemplate: 'What are the opening hours of {business}?',
    family: 'local_relevance',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['local', 'hours', 'availability'],
    priorityScore: 78,
    followupIds: ['lr-001', 'bbr-001'],
  },
  {
    id: 'lr-003',
    questionTemplate: 'Is {business} a good restaurant near me?',
    family: 'local_relevance',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['local', 'nearby', 'restaurant'],
    priorityScore: 85,
    followupIds: ['qp-002', 'bbr-004'],
  },
  {
    id: 'lr-004',
    questionTemplate: 'Does {business} serve the local community?',
    family: 'local_relevance',
    category: 'nonprofit',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['local', 'community', 'nonprofit'],
    priorityScore: 72,
    followupIds: ['btp-005', 'gd-002'],
  },
  {
    id: 'lr-005',
    questionTemplate: 'Does {business} deliver to my area?',
    family: 'local_relevance',
    category: 'ecommerce',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['local', 'delivery', 'shipping'],
    priorityScore: 80,
    followupIds: ['bbr-005', 'pv-001'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: service_clarity
  // ────────────────────────────────────────────────────────────

  {
    id: 'sc-001',
    questionTemplate: 'What services does {business} provide?',
    family: 'service_clarity',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['services', 'offerings', 'catalog'],
    priorityScore: 85,
    followupIds: ['pv-001', 'gd-004'],
  },
  {
    id: 'sc-002',
    questionTemplate: 'Does {business} offer online services or only in-person?',
    family: 'service_clarity',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['services', 'online', 'accessibility'],
    priorityScore: 72,
    followupIds: ['lr-001', 'bbr-001'],
  },
  {
    id: 'sc-003',
    questionTemplate: 'What type of cuisine does {business} serve?',
    family: 'service_clarity',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['services', 'cuisine', 'menu'],
    priorityScore: 82,
    followupIds: ['qp-002', 'qp-004'],
  },
  {
    id: 'sc-004',
    questionTemplate: 'What courses or programs does {business} offer?',
    family: 'service_clarity',
    category: 'education',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['services', 'courses', 'education'],
    priorityScore: 82,
    followupIds: ['pv-001', 'af-003'],
  },
  {
    id: 'sc-005',
    questionTemplate: 'What shipping options does {business} have?',
    family: 'service_clarity',
    category: 'ecommerce',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['services', 'shipping', 'delivery'],
    priorityScore: 78,
    followupIds: ['lr-005', 'bbr-005'],
  },
  {
    id: 'sc-006',
    questionTemplate: 'What are the main features of {business}?',
    family: 'service_clarity',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['services', 'features', 'product'],
    priorityScore: 88,
    followupIds: ['gd-006', 'df-004'],
  },
  {
    id: 'sc-007',
    questionTemplate: 'What treatments does {business} provide?',
    family: 'service_clarity',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['services', 'treatments', 'medical'],
    priorityScore: 84,
    followupIds: ['gd-007', 'pv-005'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: reputation_social_proof
  // ────────────────────────────────────────────────────────────

  {
    id: 'rsp-001',
    questionTemplate: 'What do customers say about {business}?',
    family: 'reputation_social_proof',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['reviews', 'testimonials', 'social_proof'],
    priorityScore: 92,
    followupIds: ['tc-001', 'qp-001'],
  },
  {
    id: 'rsp-002',
    questionTemplate: 'What are the most common complaints about {business}?',
    family: 'reputation_social_proof',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['reviews', 'complaints', 'negative_feedback'],
    priorityScore: 85,
    followupIds: ['df-002', 'tc-001'],
  },
  {
    id: 'rsp-003',
    questionTemplate: 'What are patient reviews of {business}?',
    family: 'reputation_social_proof',
    category: 'healthcare',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['reviews', 'patient_reviews', 'medical'],
    priorityScore: 84,
    followupIds: ['qp-005', 'tc-003'],
  },
  {
    id: 'rsp-004',
    questionTemplate: 'What are guest reviews of {business}?',
    family: 'reputation_social_proof',
    category: 'hospitality',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['reviews', 'guest_reviews', 'hospitality'],
    priorityScore: 84,
    followupIds: ['qp-003', 'tc-006'],
  },
  {
    id: 'rsp-005',
    questionTemplate: 'Has {business} won any awards or recognitions?',
    family: 'reputation_social_proof',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['reputation', 'awards', 'recognition'],
    priorityScore: 65,
    followupIds: ['tc-001', 'btp-001'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: premium_budget_perception
  // ────────────────────────────────────────────────────────────

  {
    id: 'pbp-001',
    questionTemplate: 'Is {business} a premium or budget option?',
    family: 'premium_budget_perception',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['pricing', 'positioning', 'premium_vs_budget'],
    priorityScore: 78,
    followupIds: ['pv-002', 'af-001'],
  },
  {
    id: 'pbp-002',
    questionTemplate: 'Is {business} a luxury hotel or a budget stay?',
    family: 'premium_budget_perception',
    category: 'hospitality',
    subcategory: 'hotel',
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['pricing', 'luxury', 'budget', 'hotel'],
    priorityScore: 80,
    followupIds: ['pv-002', 'qp-003'],
  },
  {
    id: 'pbp-003',
    questionTemplate: 'Is {business} a fine dining or casual restaurant?',
    family: 'premium_budget_perception',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['pricing', 'dining_tier', 'positioning'],
    priorityScore: 76,
    followupIds: ['pv-003', 'qp-002'],
  },
  {
    id: 'pbp-004',
    questionTemplate: 'Is {business} enterprise-grade or for small businesses?',
    family: 'premium_budget_perception',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['pricing', 'enterprise', 'smb', 'positioning'],
    priorityScore: 78,
    followupIds: ['pv-006', 'af-004'],
  },
  {
    id: 'pbp-005',
    questionTemplate: 'Is {business} considered affordable in its market?',
    family: 'premium_budget_perception',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['pricing', 'affordability', 'market_position'],
    priorityScore: 72,
    followupIds: ['pv-001', 'pv-002'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: audience_fit
  // ────────────────────────────────────────────────────────────

  {
    id: 'af-001',
    questionTemplate: 'Who is {business} best suited for?',
    family: 'audience_fit',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['audience', 'target_market', 'fit'],
    priorityScore: 82,
    followupIds: ['pbp-001', 'sc-001'],
  },
  {
    id: 'af-002',
    questionTemplate: 'Is {business} suitable for small businesses?',
    family: 'audience_fit',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'b2b',
    intentTags: ['audience', 'small_business', 'fit'],
    priorityScore: 78,
    followupIds: ['pv-006', 'df-006'],
  },
  {
    id: 'af-003',
    questionTemplate: 'Is {business} good for beginners?',
    family: 'audience_fit',
    category: 'education',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['audience', 'beginners', 'accessibility'],
    priorityScore: 76,
    followupIds: ['sc-004', 'pv-001'],
  },
  {
    id: 'af-004',
    questionTemplate: 'Is {business} suitable for large enterprises?',
    family: 'audience_fit',
    category: 'saas',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'enterprise',
    intentTags: ['audience', 'enterprise', 'scalability'],
    priorityScore: 75,
    followupIds: ['pbp-004', 'df-004'],
  },
  {
    id: 'af-005',
    questionTemplate: 'Is {business} family-friendly?',
    family: 'audience_fit',
    category: 'restaurant',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['audience', 'family', 'dining'],
    priorityScore: 74,
    followupIds: ['qp-002', 'pbp-003'],
  },
  {
    id: 'af-006',
    questionTemplate: 'Is {business} suitable for children?',
    family: 'audience_fit',
    category: 'entertainment',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: 'consumer',
    intentTags: ['audience', 'children', 'family'],
    priorityScore: 70,
    followupIds: ['sc-001', 'pv-001'],
  },

  // ────────────────────────────────────────────────────────────
  // FAMILY: brand_tone_personality
  // ────────────────────────────────────────────────────────────

  {
    id: 'btp-001',
    questionTemplate: 'What is the brand identity of {business}?',
    family: 'brand_tone_personality',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['brand', 'identity', 'personality'],
    priorityScore: 72,
    followupIds: ['gd-003', 'btp-002'],
  },
  {
    id: 'btp-002',
    questionTemplate: 'What kind of company is {business}?',
    family: 'brand_tone_personality',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['brand', 'company_type', 'positioning'],
    priorityScore: 75,
    followupIds: ['gd-001', 'af-001'],
  },
  {
    id: 'btp-003',
    questionTemplate: 'Is {business} a socially responsible company?',
    family: 'brand_tone_personality',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['brand', 'csr', 'values'],
    priorityScore: 60,
    followupIds: ['tc-001', 'btp-001'],
  },
  {
    id: 'btp-004',
    questionTemplate: 'Is {business} an innovative company?',
    family: 'brand_tone_personality',
    category: 'technology',
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['brand', 'innovation', 'technology'],
    priorityScore: 68,
    followupIds: ['df-001', 'gd-002'],
  },
  {
    id: 'btp-005',
    questionTemplate: 'What values does {business} stand for?',
    family: 'brand_tone_personality',
    category: null,
    subcategory: null,
    region: null,
    language: 'en',
    audienceType: null,
    intentTags: ['brand', 'values', 'mission'],
    priorityScore: 65,
    followupIds: ['btp-003', 'gd-003'],
  },
]
